// Copyright (C) 2026 Autodesk Inc.
// All rights reserved.

// API Version "version".
// This file is generated by generateTypeScript.py from NIDL.
// Do not edit.

import { core, core as adsk_core } from './core';
import { fusion, fusion as adsk_fusion } from './fusion';

declare namespace adsk {
  export import core = adsk_core;
  export import fusion = adsk_fusion;
}

export namespace sim {

  /**
    Represents an optional double value.
    @experimental
    */
  export class OptionalDouble extends core.Base {
    /**
      Returns true if the value is set, false otherwise.
      */
    readonly hasValue: boolean;
    /**
      The double value. This property is only valid if hasValue returns true.
      */
    readonly value: number;
    /**
      Creates an OptionalDouble with no value set.
      */
    static create(): OptionalDouble;
    /**
      Creates an OptionalDouble with the specified value.
      */
    static createByReal(value: number): OptionalDouble;
  }

  /**
    Simulation constraint types.
    @experimental
    */
  export const enum ConstraintTypes {
      /// Unknown constraint type.
    UnknownConstraintType,
      /// Fixed constraint type.
    FixedConstraintType,
      /// Frictionless constraint type.
    FrictionlessConstraintType,
      /// Prescribed displacement constraint type.
    PrescribedDisplacementConstraintType,
      /// Pin constraint type.
    PinConstraintType,
      /// Remote constraint type.
    RemoteConstraintType,
  }

  /**
    Object that represents a structural constraint mask.
    @experimental
    */
  export class ConstraintMaskDefinition extends core.Base {
    /**
      Whether or not the displacement along the x axis is constrained.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isDisplacementConstrainedX: boolean;
    /**
      Whether or not the displacement along the y axis is constrained.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isDisplacementConstrainedY: boolean;
    /**
      Whether or not the displacement along the z axis is constrained.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isDisplacementConstrainedZ: boolean;
    /**
      Whether or not the rotation around the x axis is constrained.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isRotationConstrainedX: boolean;
    /**
      Whether or not the rotation around the y axis is constrained.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isRotationConstrainedY: boolean;
    /**
      Whether or not the rotation around the z axis is constrained.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isRotationConstrainedZ: boolean;
    /**
      Whether or not the radial direction is constrained in cylindrical coordinates.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isConstrainedRadial: boolean;
    /**
      Whether or not the axial direction is constrained in cylindrical coordinates.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isConstrainedAxial: boolean;
    /**
      Whether or not the tangential direction is constrained in cylindrical coordinates.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isConstrainedTangential: boolean;
  }

  /**
    This class defines the methods and properties that pertain to the definition of a structural constraint.
    @experimental
    */
  export class StructuralConstraintInput extends core.Base {
    /**
      Returns the type of the structural constraint.
      */
    readonly type: ConstraintTypes;
    /**
      Gets and sets the target entities. The collection can contain vertices, edges, faces, bodies, etc.
      */
    targets: core.Base[];
  }

  /**
    Object that represents a constraint.
    @experimental
    */
  export class Constraint extends core.Base {
    /**
      The name of the constraint as displayed in the browser.
      */
    name: string;
    /**
      The entities the constraint is applied to.
      */
    readonly entities: core.Base[];
    /**
      Gets the constraint type.
      */
    readonly type: ConstraintTypes;
    /**
      Gets and sets the suppression state of this constraint.
      Suppressed constraints are excluded from the simulation solve.
      Setting this property to true suppresses the constraint; setting it to false unsuppresses it.
      Returns false on set if the constraint does not support suppression.
      */
    isSuppressed: boolean;
    /**
      Gets and sets whether this constraint is visible or not.
      Constraint visibility can be overshadowed by its parent visibility.
      When the parent is not visible, the constraint will also not be visible.
      */
    isVisible: boolean;
  }

  /**
    Object that represents a structural constraint.
    @experimental
    */
  export class StructuralConstraint extends Constraint {
    /**
      The constraint mask determines from the values in the displacement or rotation
      vectors which ones are (in)significant.
      */
    readonly maskDefinition: ConstraintMaskDefinition;
    /**
      The prescribed displacements values.
      */
    readonly displacement: core.Vector3D;
    /**
      The prescribed rotations values of the constraint.
      */
    readonly rotation: core.Vector3D;
  }

  /**
    Provides access to a collection of constraints in a load case.
    @experimental
    */
  export class Constraints extends core.Base {
    /**
      Function that returns the specified constraint using an index into the collection.
      @param index The index of the item within the collection to return. The first item in the collection has an index of 0.
      @returns Returns the specified item or null if an invalid index was specified.
      */
    item(index: number /*unsigned int*/): Constraint | null;
    /**
      Function that returns the specified constraint by name.
      @param name The name of the item within the collection to return.
      @returns Returns the specified item or null if the name is not found.
      */
    itemByName(name: string): Constraint | null;
    /**
      The number of constraints in the collection.
      */
    readonly count: number /*unsigned int*/;
    /**
      Creates a StructuralConstraintInput object that defines a fixed constraint.
      @param isDisplacementConstrainedX A boolean that indicates whether or not the displacement is constrained
      along the first axis.
      @param isDisplacementConstrainedY A boolean that indicates whether or not the displacement is constrained
      along the second axis.
      @param isDisplacementConstrainedZ A boolean that indicates whether or not the displacement is constrained
      along the third axis.
      @returns Returns the newly created StructuralConstraintInput object or null if the creation failed.
      */
    createFixedStructuralConstraintInput(isDisplacementConstrainedX: boolean, isDisplacementConstrainedY: boolean, isDisplacementConstrainedZ: boolean): StructuralConstraintInput | null;
    /**
      Creates a StructuralConstraintInput object that defines a pin constraint.
      Note: Not implemented in the current preview release.
      @param isRadial A boolean that indicates whether or not the displacement is constrained
      in the radial direction.
      @param isAxial A boolean that indicates whether or not the displacement is constrained
      in the axial direction.
      @param isTangential A boolean that indicates whether or not the displacement is constrained
      in the tangential direction.
      @returns Returns the newly created StructuralConstraintInput object or null if the creation failed.
      */
    createPinStructuralConstraintInput(isRadial: boolean, isAxial: boolean, isTangential: boolean): StructuralConstraintInput | null;
    /**
      Creates a StructuralConstraintInput object that defines a frictionless constraint.
      Note: Not implemented in the current preview release.
      @returns Returns the newly created StructuralConstraintInput object or null if the creation failed.
      */
    createFrictionlessStructuralConstraintInput(): StructuralConstraintInput | null;
    /**
      Creates a StructuralConstraintInput object that defines a prescribed displacement constraint.
      Note: Not implemented in the current preview release.
      @param isDisplacementConstrainedX A boolean that indicates whether or not the displacement is constrained
      along the first axis.
      @param isDisplacementConstrainedY A boolean that indicates whether or not the displacement is constrained
      along the second axis.
      @param isDisplacementConstrainedZ A boolean that indicates whether or not the displacement is constrained
      along the third axis.
      @param displacementX The prescribed displacement value along the first axis.
      @param displacementY The prescribed displacement value along the second axis.
      @param displacementZ The prescribed displacement value along the third axis.
      @returns Returns the newly created StructuralConstraintInput object or null if the creation failed.
      */
    createPrescribedDisplacementStructuralConstraintInput(isDisplacementConstrainedX: boolean, isDisplacementConstrainedY: boolean, isDisplacementConstrainedZ: boolean, displacementX: core.ValueInput, displacementY: core.ValueInput, displacementZ: core.ValueInput): StructuralConstraintInput | null;
    /**
      Creates a StructuralConstraintInput object that defines a remote constraint.
      Note: Not implemented in the current preview release.
      @param isDisplacementConstrainedX A boolean that indicates whether or not the displacement is constrained
      along the first axis.
      @param isDisplacementConstrainedY A boolean that indicates whether or not the displacement is constrained
      along the second axis.
      @param isDisplacementConstrainedZ A boolean that indicates whether or not the displacement is constrained
      along the third axis.
      @param displacementX The prescribed displacement value along the first axis.
      @param displacementY The prescribed displacement value along the second axis.
      @param displacementZ The prescribed displacement value along the third axis.
      @returns Returns the newly created StructuralConstraintInput object or null if the creation failed.
      */
    createRemoteStructuralConstraintInput(isDisplacementConstrainedX: boolean, isDisplacementConstrainedY: boolean, isDisplacementConstrainedZ: boolean, displacementX: core.ValueInput, displacementY: core.ValueInput, displacementZ: core.ValueInput): StructuralConstraintInput | null;
    /**
      Creates a new structural constraint based on the information provided by a StructuralConstraintInput object.
      @param input The constraint input describing the constraint to create.
      @returns Returns the newly created StructuralConstraint or null if the creation failed.
      */
    add(input: StructuralConstraintInput): StructuralConstraint | null;
    /**
      Gets and sets whether all constraints in the collection are visible or not.
      This controls the visibility of the collection as a whole.
      When the collection is made visible, each constraint retains its own visibility state.
      When the collection is hidden, all constraints are hidden.
      */
    isVisible: boolean;
  }

  /**
    Object that represents the simulations environment of a Fusion document.
    @experimental
    */
  export class Simulations extends core.Product {
    /**
      Returns the collection of simulation models in the document.
      */
    readonly simulationModels: SimulationModels;
    /**
      Returns the collection of studies in the document.
      */
    readonly studies: Studies;
    /**
      Creates a Study object that defines a simulation study without settings in the active simulation model
      and adds the Study object to the Studies collection.
      @param name The name of the study as displayed in the browser.
      @param type The type of study.
      @returns Returns the newly created Study object or null if the creation failed.
      */
    createStudy(name: string, type: StudyTypes): Study | null;
    /**
      Returns the simulation units manager for this simulations document. Use this to evaluate
      expressions, convert between units, and format values.
      */
    readonly simulationUnitsManager: SimUnitsManager;
    /**
      Returns object managing simulation default units for this simulations document.
      Use this to read and modify the active unit system and individual default units.
      */
    readonly simulationDefaultUnits: SimDefaultUnits;
  }

  /**
    Provides access to the simulation models in the simulations object.
    @experimental
    */
  export class SimulationModels extends core.Base {
    /**
      The number of simulation models.
      */
    readonly count: number /*unsigned int*/;
    /**
      Returns the specified simulation model using an index into the collection.
      @param index The index of the item within the collection to return. The first item in the collection has an index of 0.
      @returns Returns the specified item or null if an invalid index was specified.
      */
    item(index: number /*unsigned int*/): SimulationModel | null;
    /**
      Returns all simulation models with given name (as appears in the browser).
      Note: Not implemented in the current preview release.
      @param name The name (as it appears in the browser) of the simulation model.
      @returns Returns all simulation models with the specified name.
      */
    itemByName(name: string): SimulationModel[];
    /**
      Returns simulation model with the given id.
      Note: Not implemented in the current preview release.
      @param id The id of the simulation model.
      @returns Returns the simulation model with the specified id or null if no simulation model has that id.
      */
    itemById(id: string): SimulationModel | null;
  }

  /**
    Object that represents a simulation model inside the simulation workspace.
    @experimental
    */
  export class SimulationModel extends core.Base {
    /**
      The name of the simulation model as displayed in the browser.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    name: string;
    /**
      The Studies collection that provides access to existing studies in the simulation model.
      */
    readonly studies: Studies;
    /**
      The ModelComponents that provides access to Bodies/Components in the model.
      */
    readonly modelComponents: adsk.fusion.WorkingModel;
    /**
      Gets whether this simulation model is the active simulation model.
      */
    readonly isActive: boolean;
    /**
      Activates this simulation model. Activating an already active simulation model
      has no effect.
      @returns Returns true if the simulation model was successfully activated.
      */
    activate(): boolean;
    /**
      Creates a Study object that defines a simulation study without settings in the active simulation model and
      adds the Study object to the Studies collection.
      @param name The name of the study as displayed in the browser.
      @param type The type of study.
      @returns Returns the newly created Study object or null if the creation failed.
      */
    createStudy(name: string, type: StudyTypes): Study | null;
  }

  /**
    Provides access to the Studies in the simulation model.
    @experimental
    */
  export class Studies extends core.Base {
    /**
      Function that returns the specified study using an index into the collection.
      @param index The index of the item within the collection to return. The first item in the collection has an index of 0.
      @returns Returns the specified item or null if an invalid index was specified.
      */
    item(index: number /*unsigned int*/): Study | null;
    /**
      Function that returns the specified study by name.
      @param name The name of the study item within the collection to return.
      @returns Returns the specified study item or null if the name is not found.
      */
    itemByName(name: string): Study | null;
    /**
      The number of studies.
      */
    readonly count: number /*unsigned int*/;
  }

  /**
    Predefined unit systems available for simulation studies.
    @experimental
    */
  export const enum SimulationUnitSystems {
      /// Metric (SI) unit system:
      /// Length: mm, Mass: kg, Time: s, Force: N, Pressure: MPa,
      /// Temperature: K, Energy: J, Power: W, Acceleration: m/s^2, Flow Rate: CMH, Angle: deg,
      /// Velocity: m/s, Viscosity: Ns/m^2.
    MetricSIUnitSystem,
      /// U.S. (in) unit system:
      /// Length: in, Mass: lbmass, Time: s, Force: lbforce, Pressure: psi,
      /// Temperature: F, Energy: Btu, Power: Btu/s, Acceleration: ft/s^2, Flow Rate: CFM, Angle: deg,
      /// Velocity: ft/s, Viscosity: lbforce * s/ft^2.
    ImperialUnitSystem,
      /// Custom unit system that allows any combination of units per quantity.
    CustomUnitSystem,
  }

  /**
    Valid force unit types for simulation studies.
    @experimental
    */
  export const enum ForceUnits {
      /// Read-only value, resolves to the document's currently active force unit.
    DefaultForceUnit,
      /// Unknown force unit type.
    UnknownForceUnit,
      /// Newton (N).
    NewtonForceUnit,
      /// Dyne (dyne).
    DyneForceUnit,
      /// Pound-force (lbforce).
    PoundForceUnit,
      /// Ounce-force (ozforce).
    OunceForceUnit,
      /// Ton-force (tonforce).
    TonForceUnit,
  }

  /**
    Controls the default display units for simulation quantities such as force,
    pressure, and temperature at the document level.
    
    Use the unitSystem property to switch between predefined unit systems
    (Metric SI, Imperial), or set individual quantity defaults to create a
    custom unit configuration.
    
    Changes to default units are staged locally and only take effect after
    calling applyChanges.
    @experimental
    */
  export class SimDefaultUnits extends core.Base {
    /**
      Gets or sets the active unit system for the simulation document.
      Setting this immediately changes all default units to match the
      selected system (Metric SI, Imperial or Custom). Changing unit system
      to SI or Imperial clears any not applied changes for custom units.
      */
    unitSystem: SimulationUnitSystems;
    /**
      Commits all pending default-unit changes to the document.
      If any individual unit defaults have been set, the active unit system
      is automatically switched to CustomUnitSystem.
      If all staged values already match the active
      system, no switch occurs and no changes are written.
      @returns Returns true if the changes were applied successfully.
      */
    applyChanges(): boolean;
    /**
      Gets or sets the default force units for the simulation.
      Setting this stages the change locally; call applyChanges to commit.
      */
    forceUnit: ForceUnits;
  }

  /**
    Extends the base UnitsManager with helpers for converting simulation-specific
    unit enums into unit strings that the base UnitsManager methods accept.
    
    Use the inherited methods (evaluateExpression, convert, formatValue, etc.)
    for expression evaluation, unit conversion, and value formatting. The
    helper methods on this class translate typed enums (e.g. ForceUnits) into
    the string identifiers those inherited methods expect.
    
    Inherited methods that accept an optional units parameter
    (evaluateExpression, formatValue, standardizeExpression) default to
    the document's default length unit when units are omitted. Always
    pass an explicit unit string for non-length quantities.
    
    Internal values are held in SI units (e.g. seconds, radians, kg for time, angle, mass)
    with the exception that all lengths are in cm rather than meter and this affects derived
    units (e.g. force is kg * cm / s^2 -> 0.01N).
    @experimental
    */
  export class SimUnitsManager extends core.UnitsManager {
    /**
      Returns the unit string corresponding to the given force unit enum value.
      The returned string (e.g. "N", "lbforce") can be passed to base UnitsManager
      methods such as evaluateExpression, convert, and formatValue.
      @param units Optional, the force unit to convert to a string.
      @returns The unit string for the specified force unit, or null on error.
      With no argument: string for default force unit will be returned.
      */
    getForceUnitString(units?: ForceUnits/* = ForceUnits.DefaultForceUnit*/): string | null;
  }

  /**
    Load types.
    @experimental
    */
  export const enum LoadTypes {
      /// Unknown load type.
    UnknownLoadType,
      /// Pressure load type.
    PressureLoadType,
      /// Hydrostatic pressure load type.
    HydrostaticPressureLoadType,
      /// Force load type.
    ForceLoadType,
      /// Moment load type.
    MomentLoadType,
      /// Bearing load type.
    BearingLoadType,
      /// Flow rate load type.
    FlowRateLoadType,
      /// Flow velocity load type.
    FlowVelocityLoadType,
      /// Fan attribute load type.
    FanAttributeLoadType,
      /// Heat sink load type.
    HeatSinkLoadType,
      /// Gravity load type.
    GravityLoadType,
      /// Linear global load type.
    LinearGlobalLoadType,
      /// Angular global load type.
    AngularGlobalLoadType,
      /// Applied temperature load type.
    TemperatureLoadType,
      /// Thermal convection load type.
    ThermalConvectionLoadType,
      /// Thermal emissivity load type.
    RadiationLoadType,
      /// Thermal internal heat load type.
    ThermalInternalHeatLoadType,
      /// Thermal surface heat (heat source) load type.
    ThermalSurfaceHeatLoadType,
  }

  /**
    Load vector definition types.
    @experimental
    */
  export const enum VectorDefinitionTypes {
      /// Unknown vector definition type.
    UnknownVectorDefinitionType,
      /// Vector defined by the normal to the applied entity.
    NormalVectorDefinitionType,
      /// Vector defined directly by a vector.
    VectorVectorDefinitionType,
      /// Vector based on rotations around a reference geometry.
    AnglesVectorDefinitionType,
      /// Vector based on a reference geometry.
    ReferenceVectorDefinitionType,
  }

  /**
    Object that represents a transient definition.
    @experimental
    */
  export class TransientDefinition extends core.Base {
    /**
      Gets and sets the discrete curve associated with the transient definition.
      Note: Not implemented in the current preview release.
      */
    dataPoints: core.Polyline2D;
    /**
      Gets and sets whether or not the transient curve is based on real- (or pseudo-) time.
      Note: Not implemented in the current preview release.
      */
    isTimeDependent: boolean;
    /**
      Statically creates a new TransientDefinition object. This is used as input when
      defining transient loads.
      @param dataPoints The discrete curve defining the transient variations.
      @param isTimeDependent If true, the curve is interpreted as real-time, otherwise pseudo-time.
      @returns Returns the newly created TransientDefinition object or null if the creation failed.
      */
    static create(dataPoints: core.Polyline2D, isTimeDependent?: boolean/* = false*/): TransientDefinition | null;
  }

  /**
    Object that represents a vector definition.
    @experimental
    */
  export class VectorDefinition extends core.Base {
    /**
      Gets the vector definition type.
      */
    readonly type: VectorDefinitionTypes;
    /**
      Gets the magnitude of the vector.
      */
    readonly magnitude: number;
    /**
      Gets the vector as a concrete vector defined by components.
      */
    readonly vector: core.Vector3D;
    /**
      Gets the angles used in the vector definition.
      This applies when the vector definition type is AnglesVectorDefinitionType.
      */
    readonly angles: core.Vector3D;
    /**
      Gets the reference used for direction in the vector definition.
      This applies when the vector definition type is AnglesVectorDefinitionType
      or ReferenceVectorDefinitionType.
      */
    readonly reference: core.Base;
    /**
      Statically creates a new VectorDefinition object. This is used as input when
      defining directional loads.
      @param magnitude The magnitude for the vector.
      @param reference If provided, it determines the direction of which the load is applied. Otherwise
      the entity on which the load is applied implies the direction.
      @returns Returns the newly created VectorDefinition object or null if the creation failed.
      */
    static createByMagnitude(magnitude: number, reference?: core.Base/* = null*/): VectorDefinition | null;
    /**
      Statically creates a new VectorDefinition object. This is used as input when
      defining directional loads.
      @param vector The concrete vector with three components.
      @returns Returns the newly created VectorDefinition object or null if the creation failed.
      */
    static createByVector(vector: core.Vector3D): VectorDefinition | null;
    /**
      Statically creates a new VectorDefinition object. This is used as input when
      defining directional loads.
      @param magnitude The magnitude for the vector.
      @param angles The angles around the reference direction.
      @param reference If provided, it determines the direction of which the load is applied. Otherwise
      the entity on which the load is applied implies the direction.
      @returns Returns the newly created VectorDefinition object or null if the creation failed.
      */
    static createByAngles(magnitude: number, angles: core.Vector3D, reference?: core.Base/* = null*/): VectorDefinition | null;
  }

  /**
    Object that represents an angular acceleration definition.
    @experimental
    */
  export class AngularAccelerationDefinition extends core.Base {
    /**
      Statically creates a new AngularAccelerationDefinition object. This is used as input when
      defining angular global loads.
      @returns Returns the newly created AngularAccelerationDefinition object or null if the creation failed.
      */
    static create(): AngularAccelerationDefinition | null;
  }

  /**
    Object that represents a load.
    @experimental
    */
  export class Load extends core.Base {
    /**
      The name of the load as displayed in the browser.
      */
    name: string;
    /**
      The entities the load is applied to.
      */
    readonly entities: core.Base[];
    /**
      Gets the load type.
      */
    readonly type: LoadTypes;
    /**
      Gets the transient definition associated with the load.
      Note: Not implemented in the current preview release.
      */
    readonly transientDefinition: TransientDefinition;
    /**
      Gets and sets the suppression state of this load.
      Suppressed loads are excluded from the simulation solve.
      Setting this property to true suppresses the load; setting it to false unsuppresses it.
      Returns false on set if the load does not support suppression.
      */
    isSuppressed: boolean;
    /**
      Gets and sets whether this load is visible or not.
      Load visibility can be overshadowed by its parent visibility.
      When the parent is not visible, the load will also not be visible.
      */
    isVisible: boolean;
  }

  /**
    Object that represents a pressure load.
    @experimental
    */
  export class PressureLoad extends Load {
    /**
      Gets and sets the pressure value.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    pressure: number;
  }

  /**
    Object that represents a force load.
    @experimental
    */
  export class ForceLoad extends Load {
    /**
      Gets and sets the remote position for the force load.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    remotePosition: core.Vector3D;
    /**
      Gets and sets the force vector definition.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    force: VectorDefinition;
  }

  /**
    Object that represents a moment load.
    @experimental
    */
  export class MomentLoad extends Load {
    /**
      Gets and sets the remote position for the moment load.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    remotePosition: core.Vector3D;
    /**
      Gets and sets the moment vector definition.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    moment: VectorDefinition;
  }

  /**
    Object that represents a bearing load.
    @experimental
    */
  export class BearingLoad extends Load {
    /**
      Gets and sets the force vector definition.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    force: VectorDefinition;
  }

  /**
    Object that represents a fan attribute load.
    @experimental
    */
  export class FanAttributeLoad extends Load {
    /**
      Gets and sets the flow rate vector definition.
      Note: Not implemented in the current preview release.
      */
    flowRate: VectorDefinition;
    /**
      Gets and sets whether geometry simplification is applied.
      */
    isSimplify: boolean;
  }

  /**
    Object that represents a heat sink load.
    @experimental
    */
  export class HeatSinkLoad extends Load {
    /**
      Gets and sets the heat sink vector definition.
      Note: Not implemented in the current preview release.
      */
    heatSink: VectorDefinition;
    /**
      Gets and sets whether geometry simplification is applied.
      */
    isSimplify: boolean;
  }

  /**
    Object that represents a gravity load.
    @experimental
    */
  export class GravityLoad extends Load {
    /**
      Gets and sets the acceleration vector definition.
      Note: Not implemented in the current preview release.
      */
    acceleration: VectorDefinition;
  }

  /**
    Object that represents a linear global load.
    @experimental
    */
  export class LinearGlobalLoad extends Load {
    /**
      Gets and sets the acceleration vector definition.
      Note: Not implemented in the current preview release.
      */
    acceleration: VectorDefinition;
  }

  /**
    Object that represents an angular global load.
    @experimental
    */
  export class AngularGlobalLoad extends Load {
    /**
      Gets and sets the angular acceleration definition.
      Note: Not implemented in the current preview release.
      */
    acceleration: AngularAccelerationDefinition;
  }

  /**
    Object that represents a hydrostatic pressure load.
    Note: Not implemented in the current preview release.
    @experimental
    */
  export class HydrostaticPressureLoad extends Load {
  }

  /**
    Object that represents an applied temperature load.
    @experimental
    */
  export class TemperatureLoad extends Load {
    /**
      Gets and sets the applied temperature value.
      */
    temperature: number;
  }

  /**
    Object that represents a thermal convection load.
    @experimental
    */
  export class ThermalConvectionLoad extends Load {
    /**
      Gets and sets the convective heat transfer coefficient.
      */
    convectionCoefficient: number;
    /**
      Gets and sets the ambient temperature.
      */
    ambientTemperature: number;
  }

  /**
    Object that represents a thermal radiation load.
    @experimental
    */
  export class RadiationLoad extends Load {
    /**
      Gets and sets the emissivity value.
      */
    emissivity: number;
    /**
      Gets and sets the ambient temperature.
      */
    ambientTemperature: number;
  }

  /**
    Object that represents a thermal internal heat load.
    @experimental
    */
  export class ThermalInternalHeatLoad extends Load {
    /**
      Gets and sets the heat power value.
      */
    heatPower: number;
    /**
      Gets and sets whether or not the load is defined per unit volume.
      */
    isPerUnitVolume: boolean;
  }

  /**
    Object that represents a thermal surface heat (heat source) load.
    @experimental
    */
  export class ThermalSurfaceHeatLoad extends Load {
    /**
      Gets and sets the heat power value.
      */
    heatPower: number;
    /**
      Gets and sets whether or not the load is defined per unit area.
      Note: Read-only in the current preview release. Setting this property will throw.
      */
    isPerUnitArea: boolean;
  }

  /**
    Base input object used when creating a load object.
    @experimental
    */
  export class LoadInput extends core.Base {
    /**
      Gets the load type that this input will create.
      */
    readonly type: LoadTypes;
    /**
      Gets and sets the entities (faces, bodies, etc.) to which the load will be applied.
      */
    targets: core.Base[];
    /**
      Gets and sets the transient definition for time-varying loads, or null for static loads.
      */
    transientDefinition: TransientDefinition;
  }

  /**
    Input object for creating a structural load (pressure, force, moment, bearing, gravity, linear global).
    @experimental
    */
  export class StructuralLoadInput extends LoadInput {
    /**
      Gets and sets the scalar value for the load (e.g. pressure).
      */
    value: number;
    /**
      Gets and sets the vector definition for the load (magnitude, direction, reference).
      */
    vectorDefinition: VectorDefinition;
    /**
      Gets and sets the remote position at which the load is applied, when applicable.
      */
    remotePosition: core.Vector3D;
  }

  /**
    Input object for creating an angular global (angular acceleration) load.
    @experimental
    */
  export class AngularAccelerationLoadInput extends LoadInput {
    /**
      Gets and sets the angular acceleration definition.
      */
    angularAccelerationDefinition: AngularAccelerationDefinition;
  }

  /**
    Input object for creating a directional cooling load (fan attribute, heat sink).
    @experimental
    */
  export class CoolingLoadInput extends LoadInput {
    /**
      Gets and sets the flow rate vector definition (magnitude, direction, reference).
      */
    flowRate: VectorDefinition;
    /**
      Gets and sets whether geometry simplification is applied.
      */
    isSimplify: boolean;
  }

  /**
    Input object for creating thermal loads (applied temperature, thermal convection, thermal radiation, thermal internal heat, thermal surface heat (heat source)).
    @experimental
    */
  export class ThermalLoadInput extends LoadInput {
    /**
      Gets and sets the temperature value (for applied temperature load).
      */
    temperature: number;
    /**
      Gets and sets the convective heat transfer coefficient (for thermal convection load).
      */
    convectionCoefficient: number;
    /**
      Gets and sets the ambient temperature (for thermal convection or radiation loads).
      */
    ambientTemperature: number;
    /**
      Gets and sets the emissivity value (for thermal radiation load).
      */
    emissivity: number;
    /**
      Gets and sets the heat power value (for internal heat or surface heat (heat source) loads).
      */
    heatPower: number;
    /**
      Gets and sets whether the heat power is defined per unit volume (for internal heat load).
      */
    isPerUnitVolume: boolean;
    /**
      Gets and sets whether the heat power is defined per unit area (for surface heat (heat source) load).
      */
    isPerUnitArea: boolean;
  }

  /**
    Provides access to a collection of loads in a load case.
    @experimental
    */
  export class Loads extends core.Base {
    /**
      Function that returns the specified load using an index into the collection.
      @param index The index of the item within the collection to return. The first item in the collection has an index of 0.
      @returns Returns the specified item or null if an invalid index was specified.
      */
    item(index: number /*unsigned int*/): Load | null;
    /**
      Function that returns the specified load by name.
      @param name The name of the item within the collection to return.
      @returns Returns the specified item or null if the name is not found.
      */
    itemByName(name: string): Load | null;
    /**
      The number of loads in the collection.
      */
    readonly count: number /*unsigned int*/;
    /**
      Creates an input object for adding a pressure load.
      @param entities The entities to apply the load to.
      @param pressure The pressure value.
      @returns The pressure load input, or null if creation failed.
      */
    createPressureLoadInput(entities: core.Base[], pressure: number): StructuralLoadInput | null;
    /**
      Creates an input object for adding a force load.
      @param entities The entities to apply the load to.
      @param force The force vector definition.
      @returns The force load input, or null if creation failed.
      */
    createForceLoadInput(entities: core.Base[], force: VectorDefinition): StructuralLoadInput | null;
    /**
      Creates an input object for adding a moment load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param moment The moment vector definition.
      @returns The moment load input, or null if creation failed.
      */
    createMomentLoadInput(entities: core.Base[], moment: VectorDefinition): StructuralLoadInput | null;
    /**
      Creates an input object for adding a bearing load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param force The force vector definition.
      @returns The bearing load input, or null if creation failed.
      */
    createBearingLoadInput(entities: core.Base[], force: VectorDefinition): StructuralLoadInput | null;
    /**
      Creates an input object for adding a gravity load (body load per unit mass).
      Note: Not implemented in the current preview release.
      @param gravityAcceleration The gravity acceleration vector definition.
      @returns The gravity load input, or null if creation failed.
      */
    createGravityLoadInput(gravityAcceleration: VectorDefinition): StructuralLoadInput | null;
    /**
      Creates an input object for adding a linear global (linear acceleration) load.
      Note: Not implemented in the current preview release.
      @param linearAcceleration The linear acceleration vector definition.
      @returns The linear global load input, or null if creation failed.
      */
    createLinearGlobalLoadInput(linearAcceleration: VectorDefinition): StructuralLoadInput | null;
    /**
      Creates an input object for adding an angular global (angular acceleration) load.
      Note: Not implemented in the current preview release.
      @param angularAccelerationDefinition The angular acceleration definition.
      @returns The angular global load input, or null if creation failed.
      */
    createAngularGlobalLoadInput(angularAccelerationDefinition: AngularAccelerationDefinition): AngularAccelerationLoadInput | null;
    /**
      Creates an input object for adding a fan attribute (directed flow) load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param flowRate The flow rate vector definition.
      @returns The fan attribute load input, or null if creation failed.
      */
    createFanAttributeInput(entities: core.Base[], flowRate: VectorDefinition): CoolingLoadInput | null;
    /**
      Creates an input object for adding a heat sink load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @returns The heat sink load input, or null if creation failed.
      */
    createHeatSinkInput(entities: core.Base[]): CoolingLoadInput | null;
    /**
      Creates an input object for adding an applied temperature load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param temperature The applied temperature value.
      @returns The applied temperature load input, or null if creation failed.
      */
    createTemperatureLoadInput(entities: core.Base[], temperature: number): ThermalLoadInput | null;
    /**
      Creates an input object for adding a thermal convection load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param convectionCoefficient The convective heat transfer coefficient.
      @param ambientTemperature The ambient temperature.
      @returns The thermal convection load input, or null if creation failed.
      */
    createThermalConvectionLoadInput(entities: core.Base[], convectionCoefficient: number, ambientTemperature: number): ThermalLoadInput | null;
    /**
      Creates an input object for adding a thermal radiation load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param emissivity The emissivity value.
      @param ambientTemperature The ambient temperature.
      @returns The thermal radiation load input, or null if creation failed.
      */
    createThermalRadiationLoadInput(entities: core.Base[], emissivity: number, ambientTemperature: number): ThermalLoadInput | null;
    /**
      Creates an input object for adding a thermal internal heat load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param heatPower The heat power value.
      @param isPerUnitVolume True if the heat power is per unit volume.
      @returns The thermal internal heat load input, or null if creation failed.
      */
    createThermalInternalHeatLoadInput(entities: core.Base[], heatPower: number, isPerUnitVolume: boolean): ThermalLoadInput | null;
    /**
      Creates an input object for adding a thermal surface heat (heat source) load.
      Note: Not implemented in the current preview release.
      @param entities The entities to apply the load to.
      @param heatPower The heat power value.
      @param isPerUnitArea True if the heat power is per unit area.
      @returns The thermal surface heat (heat source) load input, or null if creation failed.
      */
    createThermalSurfaceHeatLoadInput(entities: core.Base[], heatPower: number, isPerUnitArea: boolean): ThermalLoadInput | null;
    /**
      Adds a load to the collection using the given load input. Creates the Load object and returns it.
      @param input The load input describing the load to create.
      @returns The newly created Load, or null if creation failed.
      */
    add(input: LoadInput): Load | null;
    /**
      Gets and sets whether all loads in the collection are visible or not.
      This controls the visibility of the collection as a whole.
      When the collection is made visible, each load retains its own visibility state.
      When the collection is hidden, all loads are hidden.
      */
    isVisible: boolean;
  }

  /**
    Provides access to contacts in a study.
    @experimental
    */
  export class Contacts extends core.Base {
    /**
      The number of contacts.
      */
    readonly count: number /*unsigned int*/;
    /**
      Returns the contact at the specified index.
      */
    item(index: number /*unsigned int*/): Contact;
    /**
      Runs automatic contact generation for this study.
      Uses contact detection tolerance for autodetection of contacts.
      For supported study types, its value can be changed in study general settings.
      */
    autoGenerate(): boolean;
    /**
      Creates an input object for adding a bonded contact set.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns bonded contact input, or null if creation failed.
      */
    createBondedContactInput(isSymmetric: boolean, maxActivationDistance: OptionalDouble): ContactInput | null;
    /**
      Creates an input object for adding a separation contact set. Separation contacts allow
      surfaces to separate and come back into contact, with optional friction.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @param coefficientOfStaticFriction The coefficient of static friction between the contacting surfaces.
      Only applicable in Static Stress and Thermal Stress study types.
      @returns Returns separation contact input, or null if creation failed.
      */
    createSeparationContactInput(isSymmetric: boolean, maxActivationDistance: OptionalDouble, coefficientOfStaticFriction?: OptionalDouble/* = null*/): ContactInput | null;
    /**
      Creates an input object for adding a sliding contact set. Sliding contacts allow
      tangential motion between surfaces while preventing normal separation.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns sliding contact input, or null if creation failed.
      */
    createSlidingContactInput(isSymmetric: boolean, maxActivationDistance: OptionalDouble): ContactInput | null;
    /**
      Creates an input object for adding a rough contact set. Rough contacts prevent all
      relative tangential motion (infinite friction) while allowing normal separation.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns rough contact input, or null if creation failed.
      */
    createRoughContactInput(isSymmetric: boolean, maxActivationDistance: OptionalDouble): ContactInput | null;
    /**
      Creates an input object for adding an offset bonded contact set. Offset bonded contacts
      are similar to bonded contacts but allow an offset between the contacting surfaces.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns offset bonded contact input, or null if creation failed.
      */
    createOffsetBondedContactInput(isSymmetric: boolean, maxActivationDistance: OptionalDouble): ContactInput | null;
    /**
      Adds a contact to the collection using the given contact input. Creates the Contact object and returns it.
      @param input The contact input describing the contact to create.
      @returns The newly created Contact, or null if creation failed.
      */
    add(input: ContactInput): Contact | null;
  }

  /**
    Contact types
    @experimental
    */
  export const enum ContactTypes {
      /// Unknown contact type.
    UnknownContactType,
      /// Bonded contact.
    BondedContactType,
      /// Offset bonded contact.
    OffsetBondedContactType,
      /// Separation contact.
    SeparationContactType,
      /// Sliding contact.
    SlidingContactType,
      /// Rough contact.
    RoughContactType,
      /// Free contact.
    FreeContactType,
  }

  /**
    Base class for contacts.
    @experimental
    */
  export class ContactBase extends core.Base {
    /**
      The name of the contact as displayed in the browser.
      */
    name: string;
    /**
      The entities the contact is applied to. Provide union of primary
      and secondary selection sets for contact.
      */
    readonly entities: core.Base[];
    /**
      The type of contact.
      */
    readonly type: ContactTypes;
    /**
      Gets the information if contact is manual vs. autogenerated
      */
    readonly isManual: boolean;
    /**
      Gets the primary body selection
      */
    readonly primaryEntities: core.Base[];
    /**
      Gets the secondary body selection
      */
    readonly secondaryEntities: core.Base[];
    /**
      Gets and sets the suppression state of this contact.
      Suppressed contacts are excluded from the simulation solve.
      Setting this property to true suppresses the contact; setting it to false unsuppresses it.
      Returns false on set if the contact does not support suppression.
      */
    isSuppressed: boolean;
    /**
      Deletes the contact.
      @returns True when deletion succeeded, false otherwise. Deleting an automatic
      contact is not supported and returns false.
      */
    deleteMe(): boolean;
  }

  /**
    Contact class with methods for reading and modifying contact properties
    
    Setter methods on this class accept OptionalDouble parameters. OptionalDouble is a wrapper
    around a double value that can either hold an explicit value or be empty:
    - An OptionalDouble created with a value (OptionalDouble.createByReal) sets the property to that specific value.
    - An empty OptionalDouble (OptionalDouble.create) or null clears the property, meaning the solver
      will determine the appropriate value automatically.
    
    Contact configuration is split into transactional operations:
    - setTo* methods change the contact type and its fundamental parameters (symmetry, activation distance).
    - setActivationDistances, setContactStiffness, and setThermalConductance modify advanced properties
      without changing the contact type.
    Contact properties are study-type specific. For event simulation studies (dynamic and quasi-static),
    only base read operations are supported. For other study types, inapplicable parameters (e.g thermal conductance)
    can be read (return null) and modifying them has no effect.
    @experimental
    */
  export class Contact extends ContactBase {
    /**
      Gets whether symmetric penetration is used.
      */
    readonly isSymmetric: boolean;
    /**
      Gets whether the maximum activation distance is automatically calculated.
      */
    readonly isAutoMaxActivationDistance: boolean;
    /**
      Gets the stiffness factor property.
      */
    readonly stiffnessFactor: OptionalDouble;
    /**
      Gets the coefficient of static friction property.
      */
    readonly coefficientOfStaticFriction: OptionalDouble;
    /**
      Gets the maximum activation distance property.
      */
    readonly maxActivationDistance: OptionalDouble;
    /**
      Gets the thermal conductance property.
      */
    readonly thermalConductance: OptionalDouble;
    /**
      Gets the penetration surface offset property.
      */
    readonly penetrationSurfaceOffset: OptionalDouble;
    /**
      Gets the maximum allowable penetration property.
      */
    readonly maxAllowablePenetration: OptionalDouble;
    /**
      Gets the frictional stiffness for stick property.
      */
    readonly frictionalStiffnessForStick: OptionalDouble;
    /**
      Gets the maximum allowable adjustment ratio property.
      */
    readonly maxAllowableAdjustmentRatio: OptionalDouble;
    /**
      Gets the allowable penetration lower bound ratio property.
      */
    readonly allowablePenetrationLowerBoundRatio: OptionalDouble;
    /**
      Gets the maximum radial activation distance property.
      */
    readonly maxRadialActivationDistance: OptionalDouble;
    /**
      Gets the maximum normal activation distance property.
      */
    readonly maxNormalActivationDistance: OptionalDouble;
    /**
      Gets the maximum allowable slip property.
      */
    readonly maxAllowableSlip: OptionalDouble;
    /**
      Sets the contact type to bonded. Bonded contacts prevent relative motion between
      the contacting surfaces.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns true if the contact type was successfully changed.
      */
    setToBonded(isSymmetric: boolean, maxActivationDistance: OptionalDouble): boolean;
    /**
      Sets the contact type to separation. Separation contacts allow surfaces to separate
      and come back into contact, with optional friction.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @param coefficientOfStaticFriction The coefficient of static friction between the contacting surfaces.
      Only applicable in Static Stress and Thermal Stress study types.
      @returns Returns true if the contact type was successfully changed.
      */
    setToSeparation(isSymmetric: boolean, maxActivationDistance: OptionalDouble, coefficientOfStaticFriction?: OptionalDouble/* = null*/): boolean;
    /**
      Sets the contact type to sliding. Sliding contacts allow tangential motion
      between surfaces while preventing normal separation.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns true if the contact type was successfully changed.
      */
    setToSliding(isSymmetric: boolean, maxActivationDistance: OptionalDouble): boolean;
    /**
      Sets the contact type to rough. Rough contacts prevent all relative tangential
      motion (infinite friction) while allowing normal separation.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns true if the contact type was successfully changed.
      */
    setToRough(isSymmetric: boolean, maxActivationDistance: OptionalDouble): boolean;
    /**
      Sets the contact type to offset bonded. Offset bonded contacts are similar to bonded
      contacts but allow an offset between the contacting surfaces.
      @param isSymmetric When true, both surfaces are checked for penetration; when false, only one-sided checking is performed.
      @param maxActivationDistance The maximum activation distance for contact detection. Null or empty enables automatic calculation.
      @returns Returns true if the contact type was successfully changed.
      */
    setToOffsetBonded(isSymmetric: boolean, maxActivationDistance: OptionalDouble): boolean;
    /**
      Sets the radial and normal activation distance overrides for the contact.
      Applicable to all study types and all contact types.
      @param maxRadialActivationDistance The maximum radial activation distance.
      @param maxNormalActivationDistance The maximum normal activation distance.
      @returns Returns true if the activation distances were successfully updated.
      */
    setActivationDistances(maxRadialActivationDistance: OptionalDouble, maxNormalActivationDistance: OptionalDouble): boolean;
    /**
      Sets the contact stiffness and penetration properties.
      @param stiffnessFactor The stiffness scaling factor for the contact.
      @param penetrationSurfaceOffset The initial penetration or gap offset between contacting surfaces.
      @param maxAllowablePenetration The maximum allowable penetration depth. Only applicable in Static Stress and Thermal Stress
      studies; ignored for other study types.
      @param frictionalStiffnessForStick The frictional stiffness used for stick behavior. Not applicable and ignored in Thermal studies.
      @returns Returns true if the stiffness properties were successfully updated.
      */
    setContactStiffness(stiffnessFactor: OptionalDouble, penetrationSurfaceOffset: OptionalDouble, maxAllowablePenetration?: OptionalDouble/* = null*/, frictionalStiffnessForStick?: OptionalDouble/* = null*/): boolean;
    /**
      Sets the thermal conductance for the contact. Thermal conductance controls the rate
      of heat transfer across the contact interface.
      Only applicable in Thermal Stress and Thermal study types.
      @param thermalConductance The thermal conductance value for heat transfer across the contact.
      @returns Returns true if the operation succeeded. For study types that do not support
      thermal conductance, returns true but has no effect.
      */
    setThermalConductance(thermalConductance: OptionalDouble): boolean;
  }

  /**
    This class defines the methods and properties that pertain to the definition of a contact.
    Created via Contacts.create*ContactInput methods. After creation, advanced properties
    can be configured before passing the input to Contacts.add().
    
    Read-only properties (type, isSymmetric, isAutoMaxActivationDistance, maxActivationDistance,
    coefficientOfStaticFriction) are set by the create method and reflect the contact's
    fundamental configuration. Settable properties allow configuring advanced solver parameters
    before the contact is created.
    @experimental
    */
  export class ContactInput extends core.Base {
    /**
      Returns the type of the contact.
      */
    readonly type: ContactTypes;
    /**
      Gets whether symmetric penetration checking is used.
      */
    readonly isSymmetric: boolean;
    /**
      Gets whether the maximum activation distance is automatically calculated.
      */
    readonly isAutoMaxActivationDistance: boolean;
    /**
      Gets the maximum activation distance for contact detection.
      */
    readonly maxActivationDistance: OptionalDouble;
    /**
      Gets the coefficient of static friction.
      */
    readonly coefficientOfStaticFriction: OptionalDouble;
    /**
      Gets or sets the primary entities selection.
      All entities must be faces belonging to the same body.
      Primary and secondary sets can not share any faces.
      */
    primaryEntities: core.Base[];
    /**
      Gets or sets the secondary entities selection.
      All entities must be faces belonging to the same body.
      Primary and secondary sets can not share any faces.
      */
    secondaryEntities: core.Base[];
    /**
      Gets or sets the stiffness factor property.
      */
    stiffnessFactor: OptionalDouble;
    /**
      Gets or sets the thermal conductance property.
      Only applicable in Thermal Stress and Thermal study types.
      */
    thermalConductance: OptionalDouble;
    /**
      Gets or sets the penetration surface offset property.
      */
    penetrationSurfaceOffset: OptionalDouble;
    /**
      Gets or sets the maximum allowable penetration property.
      Only applicable in Static Stress and Thermal Stress studies.
      */
    maxAllowablePenetration: OptionalDouble;
    /**
      Gets or sets the frictional stiffness for stick property.
      Not applicable in Thermal studies.
      */
    frictionalStiffnessForStick: OptionalDouble;
    /**
      Gets or sets the maximum radial activation distance property.
      */
    maxRadialActivationDistance: OptionalDouble;
    /**
      Gets or sets the maximum normal activation distance property.
      */
    maxNormalActivationDistance: OptionalDouble;
  }

  /**
    Simulation study types.
    @experimental
    */
  export const enum StudyTypes {
      /// Unknown study type.
    UnknownStudyType,
      /// Structural linear static stress simulation study type.
    LinearStaticStressStudyType,
      /// Structural nonlinear static stress simulation study type.
    NonLinearStaticStressStudyType,
      /// Structural dynamic event simulation study type.
    DynamicEventSimulationStudyType,
      /// Modal frequencies simulation study type.
    ModalFrequenciesStudyType,
      /// Electronics cooling simulation study type.
    ElectronicsCoolingStudyType,
      /// Thermal simulation study type.
    ThermalStudyType,
      /// Thermal stress simulation study type.
    ThermalStressStudyType,
      /// Structural buckling simulation study type.
    StructuralBucklingStudyType,
      /// Quasi-static event simulation study type.
    QuasiStaticEventSimulationStudyType,
      /// Shape optimization simulation study type.
    ShapeOptimizationStudyType,
      /// Injection molding simulation study type.
    InjectionMoldingStudyType,
  }

  /**
    Pre-check state indicating whether the study is ready to solve.
    @experimental
    */
  export const enum PrecheckStates {
      /// The pre-check status has not been computed yet or is unknown.
    UnknownPrecheckState,
      /// The study is ready to solve with no issues.
    ReadyToSolvePrecheckState,
      /// The study is ready to solve but has warnings that should be reviewed.
    ReadyToSolveWithWarningsPrecheckState,
      /// The study is not ready to solve due to errors that must be fixed.
    NotReadyToSolvePrecheckState,
  }

  /**
    Severity level of a pre-check message.
    @experimental
    */
  export const enum PrecheckMessageSeverities {
      /// Informational message indicating the study passed validation.
    InformationPrecheckMessageSeverity,
      /// Warning message that does not prevent solving but should be reviewed.
    WarningPrecheckMessageSeverity,
      /// Critical error message that prevents the study from being solved.
    ErrorPrecheckMessageSeverity,
  }

  /**
    The state of the study's solve results.
    @experimental
    */
  export const enum StudyResultStates {
      /// The result state is unknown or has not been computed yet.
    UnknownResultState,
      /// No results are available. The study has not been solved.
    NoResultState,
      /// Results are available and up to date with the current study definition.
    UpToDateResultState,
      /// Results are available but the study has been modified since the last solve.
    OutOfDateResultState,
      /// The last solve failed with errors.
    FailedResultState,
      /// A solve is currently in progress.
    SolvingResultState,
  }

  /**
    Object that represents a study inside a simulation model.
    @experimental
    */
  export class Study extends core.Base {
    /**
      The type of study.
      */
    readonly type: StudyTypes;
    /**
      The name of the study as displayed in the browser.
      */
    name: string;
    /**
      The LoadCases collection that provides access to existing load cases in the study.
      */
    readonly loadCases: LoadCases;
    /**
      All settings for this study.
      */
    readonly settings: Settings;
    /**
      Gets the current pre-check state of the study indicating whether it is ready to solve.
      */
    readonly precheckState: PrecheckStates;
    /**
      Gets the pre-check messages (errors and warnings) for this study.
      Note: After fixing issues, this property must be queried again to retrieve
      updated messages. Stored results are not automatically refreshed.
      */
    readonly precheckMessages: PrecheckMessage[];
    /**
      Gets whether this study is the active study in the simulation model.
      */
    readonly isActive: boolean;
    /**
      Activates this study.
      */
    activate(): boolean;
    /**
      The Contacts collection that provides access to existing contacts in the study.
      */
    readonly contacts: Contacts;
    /**
      Creates a copy of this study.
      @returns Returns the newly created Study or null if cloning failed.
      */
    clone(): Study | null;
    /**
      Returns the study materials for all bodies in the study.
      */
    readonly materials: StudyMaterial[];
    /**
      Deletes this study from the simulation model.
      This operation is not undoable.
      @returns Returns true if the delete was successful.
      */
    deleteMe(): boolean;
    /**
      Initiates a solve operation for this study.
      Currently only Linear Static Stress studies are supported. Attempting to
      solve any other study type will throw an exception.
      Before calling solve, check the precheck state to ensure the study is ready.
      The study must not have NotReadyToSolvePrecheckState, UpToDateResultState,
      SolvingResultState, or FailedResultState.
      @returns Returns a SolveFuture object that can be used to monitor the solve operation,
      or null if the solve could not be initiated.
      */
    solve(): SolveFuture | null;
    /**
      Gets the current state of this study's solve results.
      */
    readonly resultState: StudyResultStates;
  }

  /**
    Represents the asynchronous result of a solve operation.
    This object is returned by Study.solve() and can be used to monitor
    the state of the solve, check for errors or warnings, and cancel the operation.
    @experimental
    */
  export class SolveFuture extends core.Future {
    /**
      Returns true if the solve operation has completed, regardless of whether
      it succeeded or failed.
      */
    readonly isComplete: boolean;
    /**
      Returns true if the solve operation completed successfully with no errors.
      Returns false otherwise, including when the solve is still in progress.
      */
    readonly isSucceeded: boolean;
    /**
      Returns true if the solve job completed with errors.
      Returns false otherwise, including when the solve is still in progress.
      */
    readonly hasErrors: boolean;
    /**
      Returns true if the solve job completed with warnings.
      Returns false otherwise, including when the solve is still in progress.
      */
    readonly hasWarnings: boolean;
    /**
      Returns any error messages from the solve operation.
      Returns an empty string if there are no errors or the solve is still in progress.
      */
    readonly errors: string;
    /**
      Returns any warning messages from the solve operation.
      Returns an empty string if there are no warnings or the solve is still in progress.
      */
    readonly warnings: string;
    /**
      The progress of the solve operation as a percentage value between 0 and 100.
      */
    readonly progressPercentage: number /*int*/;
    /**
      Cancels the solve operation if it is still in progress.
      This operation is not undoable.
      @returns Returns true if the cancellation was successfully requested, false otherwise.
      */
    cancel(): boolean;
  }

  /**
    Represents a single pre-check validation message (error or warning).
    @experimental
    */
  export class PrecheckMessage extends core.Base {
    /**
      The severity level of this message.
      */
    readonly severity: PrecheckMessageSeverities;
    /**
      The text content of the message describing the issue or information.
      */
    readonly message: string;
    /**
      Gets the suggested resolution descriptions (actionable steps) to fix this validation issue.
      Each string provides a description of an action the user can take to resolve the problem.
      For example: "Click here to toggle Gravity" or "Add a constraint to the load case".
      */
    readonly resolutions: string[];
  }

  /**
    Material safety factor types.
    @experimental
    */
  export const enum SafetyFactorTypes {
      /// The method to calculate the factor of safety is based on the yield strength.
    YieldStrengthSafetyFactorType,
      /// The method to calculate the factor of safety is based on the ultimate tensile strength.
    UltimateTensileStrengthSafetyFactorType,
  }

  /**
    Provides access to the study material.
    @experimental
    */
  export class StudyMaterial extends core.Base {
    /**
      Indicates whether the original design material was used or the material is overridden by the study.
      */
    readonly isModelMaterial: boolean;
    /**
      Gets or sets the safety factor type used for this material in safety factor calculations.
      */
    safetyFactorType: SafetyFactorTypes;
    /**
      Reverts this material to the original design model material, removing any study-specific override.
      This is a no-op if already using the model material.
      @returns Returns true if the material was successfully reverted or was already the model material.
      */
    revertToModelMaterial(): boolean;
    /**
      Assigns a new material to the body associated with this StudyMaterial, overriding any current material assignment.
      The material can be from a material library or a document material.
      @param material The material to assign.
      @returns Returns true if the material was successfully assigned.
      */
    assignMaterial(material: core.Material): boolean;
    /**
      Gets the core Material object for the current study material (override if present, otherwise the model material).
      */
    readonly material: core.Material;
    /**
      Gets the material category (e.g. "Metal", "Plastic").
      */
    readonly category: string;
    /**
      Gets whether the current study material is valid for this study type.
      A value of false indicates that material values are out of limits and simulation cannot be performed.
      */
    readonly isMaterialValid: boolean;
    /**
      Gets the design body that this study material is assigned to.
      Returns null if the body cannot be resolved.
      */
    readonly body: fusion.BRepBody;
  }

  /**
    Provides access to the LoadCases in the study.
    @experimental
    */
  export class LoadCases extends core.Base {
    /**
      Function that returns the specified load case using an index into the collection.
      @param index The index of the item within the collection to return. The first item in the collection has an index of 0.
      @returns Returns the specified item or null if an invalid index was specified.
      */
    item(index: number /*unsigned int*/): LoadCase | null;
    /**
      Function that returns the specified load case by name.
      Note: Not implemented in the current preview release.
      @param name The name of the load case within the collection to return.
      @returns Returns the specified load case or null if the name is not found.
      */
    itemByName(name: string): LoadCase | null;
    /**
      The number of load cases.
      */
    readonly count: number /*unsigned int*/;
  }

  /**
    Object that represents a LoadCase inside a study.
    @experimental
    */
  export class LoadCase extends core.Base {
    /**
      The name of the load case as displayed in the browser.
      */
    name: string;
    /**
      The Constraints collection that provides access to existing constraints in the load case.
      */
    readonly constraints: Constraints;
    /**
      The Loads collection that provides access to existing loads in the load case.
      */
    readonly loads: Loads;
    /**
      Gets whether this load case is the active load case in the study.
      */
    readonly isActive: boolean;
    /**
      Activates this load case.
      @returns Returns true if the load case was successfully activated.
      */
    activate(): boolean;
    /**
      Creates a copy of this load case in the same study.
      @returns Returns the newly created LoadCase or null if cloning failed.
      */
    clone(): LoadCase | null;
    /**
      Gets and sets the suppression state of this load case.
      Suppressed load cases are excluded from the simulation solve.
      Setting this property to true suppresses the load case; setting it to false unsuppresses it.
      Returns false on set if the load case does not support suppression
      (for example, the last unsuppressed load case in a study).
      */
    isSuppressed: boolean;
    /**
      Gets and sets whether all items in the load case are visible or not.
      This controls the visibility of the group as a whole.
      When the load case is made visible, each item retains its own visibility state.
      When the load case is hidden, all items are hidden.
      */
    isVisible: boolean;
  }

  /**
    Determination of the average element size.
    @experimental
    */
  export const enum ElementSizeDeterminationTypes {
      /// Unknown element size determination type.
    UnknownElementSizeDeterminationType,
      /// Average element size as a proportion of the model size.
    SizeByModelElementSizeDeterminationType,
      /// An absolute value for the average element size.
    AbsoluteElementSizeDeterminationType,
  }

  /**
    Mesh element order types.
    @experimental
    */
  export const enum ElementOrderTypes {
      /// Unknown element order type.
    UnknownElementOrderType,
      /// Linear element order type.
    LinearElementOrderType,
      /// Parabolic (quadratic) element order type.
    ParabolicElementOrderType,
  }

  /**
    Object that represents simulation mesh settings.
    @experimental
    */
  export class MeshSettings extends core.Base {
    /**
      Default mesh elements order.
      */
    elementOrderType: ElementOrderTypes;
    /**
      Average element size determination policy.
      */
    elementSizeDeterminationType: ElementSizeDeterminationTypes;
    /**
      The ratio of the model size as the average element size.
      */
    modelBasedElementSize: number;
    /**
      The absolute value for the average element size.
      */
    absoluteElementSize: number;
    /**
      The minimum element size as a fraction of the average element size. Valid range is 0.01 to 1.0.
      */
    minElementSize: number;
    /**
      Maximum aspect ratio of the elements.
      */
    maxAspectRatio: number;
    /**
      Whether element shapes follow curved and rounded faces of the geometry.
      Only applies when elementOrderType is Parabolic.
      */
    isCreatingCurvedMeshElements: boolean;
    /**
      Whether element size is relative to each part's bounding box rather than the assembly bounding box.
      */
    isScalingMeshSizePerPart: boolean;
    /**
      The maximum turn angle.
      */
    maxTurnAngle: number;
    /**
      Maximum adjacent mesh size ratio.
      */
    maxAdjacentMeshSizeRatio: number;
  }

  /**
    Object that represents simulation general settings.
    @experimental
    */
  export class GeneralSettings extends core.Base {
    /**
      Whether or not rigid body modes are removed.
      */
    removeRigidBodyModes: boolean;
    /**
      The value of contact detection tolerance for solids used for automatic contacts generation
      */
    contactDetectionTolerance: number;
  }

  /**
    Object that represents simulation solve settings.
    @experimental
    */
  export class SolveSettings extends core.Base {
    /**
      Placeholder.
      Note: Not implemented in the current preview release.
      */
    placeholder: number;
  }

  /**
    Object that represents all simulation settings.
    @experimental
    */
  export class Settings extends core.Base {
    /**
      General settings.
      */
    readonly generalSettings: GeneralSettings;
    /**
      Mesh settings.
      */
    readonly meshSettings: MeshSettings;
    /**
      Solve settings.
      */
    readonly solveSettings: SolveSettings;
    /**
      Apply settings.
      */
    applyChanges(): boolean;
  }
}

