// Copyright (C) 2026 Autodesk Inc.
// All rights reserved.

// API Version "version".
// This file is generated by generateTypeScript.py from NIDL.
// Do not edit.

import { core, core as adsk_core } from './core';

declare namespace adsk {
  export import core = adsk_core;
}

export namespace drawing {

  /**
    Specifies the different drawing units that can be used.
    The unit type affects dimension display, annotations, and measurements throughout the drawing.
    @experimental
    */
  export const enum DrawingUnitTypes {
      /// Specifies that the drawing uses inch units.
      /// Commonly used with ASME (American Society of Mechanical Engineers) drawing standards.
      /// All dimensions and measurements in the drawing will be displayed in inches.
    InchDrawingUnitType,
      /// Specifies that the drawing uses millimeter units.
      /// Commonly used with ISO (International Organization for Standardization) drawing standards.
      /// All dimensions and measurements in the drawing will be displayed in millimeters.
    MillimeterDrawingUnitType,
  }

  /**
    Specifies the different drawing standards that can be used.
    The standard defines projection angle, dimension styles, title block format, and annotation conventions.
    @experimental
    */
  export const enum DrawingStandardTypes {
      /// ISO standard using first-angle projection.
    ISODrawingStandardType,
      /// ASME standard using third-angle projection. Common in North America.
    ASMEDrawingStandardType,
  }

  /**
    Specifies the sheet size for a drawing document.
    @experimental
    */
  export const enum SheetSizes {
    CustomSizeSheetSize,
    A4ISOSheetSize,
    A3ISOSheetSize,
    A2ISOSheetSize,
    A1ISOSheetSize,
    A0ISOSheetSize,
    AASMESheetSize,
    BASMESheetSize,
    CASMESheetSize,
    DASMESheetSize,
    EASMESheetSize,
  }

  /**
    Specifies the sheet orientation for printing and display.
    @experimental
    */
  export const enum SheetOrientationTypes {
    LandscapeSheetOrientationType,
    PortraitSheetOrientationType,
  }

  /**
    Specifies the base document option for drawing creation.
    @experimental
    */
  export const enum BaseDocumentTypes {
    FromScratchBaseDocumentType,
      /// Create drawing from a template
    FromTemplateBaseDocumentType,
  }

  /**
    Specifies the mode of drawing creation.
    @experimental
    */
  export const enum DrawingCreationModes {
    AutomaticDrawingCreationMode,
      /// Create manual drawing with user-defined views and annotations.
      /// Note: This option is not currently supported. Use AutomaticDrawingCreationMode instead.
    ManualDrawingCreationMode,
  }

  /**
    Specifies which components get drawing sheets generated.
    @experimental
    */
  export const enum SheetCreationTypes {
    FirstLevelOnlySheetCreationType,
    AllLevelsSheetCreationType,
  }

  /**
    Specifies which assembly content is used when creating automatic drawing sheets (API supports
    Full Assembly and Visible Only mode).
    @experimental
    */
  export const enum DrawingContentTypes {
    FullAssemblyDrawingContentType,
    VisibleOnlyDrawingContentType,
  }

  /**
    Corner location options for tables on sheets. Used for parts lists, bend tables, and other sheet tables.
    @experimental
    */
  export const enum TableLocationTypes {
    TopLeftTableLocationType,
    TopRightTableLocationType,
    BottomLeftTableLocationType,
    BottomRightTableLocationType,
  }

  /**
    Dimension placement strategy for automatic dimensioning.
    @experimental
    */
  export const enum DimensionStrategyTypes {
    OverallDimensionStrategyType,
    AutomaticDimensionStrategyType,
    BaselineDimensionStrategyType,
    ChainDimensionStrategyType,
  }

  /**
    Hole and thread annotation preferences.
    @experimental
    */
  export const enum HolePreferencesTypes {
    HoleAndThreadNoteHolePreferencesType,
    HoleNoteOnlyHolePreferencesType,
    ThreadNoteOnlyHolePreferencesType,
    NoHoleAnnotationsHolePreferencesType,
  }

  /**
    Default origin (datum) point for component dimension placement.
    @experimental
    */
  export const enum DefaultOriginTypes {
    ModelOriginDefaultOriginType,
    BottomLeftDefaultOriginType,
    BottomRightDefaultOriginType,
    TopLeftDefaultOriginType,
    TopRightDefaultOriginType,
  }

  /**
    Visual rendering style for drawing views.
    @experimental
    */
  export const enum DrawingViewStyleTypes {
    VisibleEdgesDrawingViewStyleType,
    VisibleAndHiddenEdgesDrawingViewStyleType,
    ShadedDrawingViewStyleType,
    ShadedWithVisibleEdgesDrawingViewStyleType,
  }

  /**
    Tangent edge display options.
    @experimental
    */
  export const enum TangentEdgeDisplayTypes {
    OffTangentEdgeDisplayType,
    OnTangentEdgeDisplayType,
    ForeshortenedTangentEdgeDisplayType,
  }

  /**
    Center mark display options for circular features.
    @experimental
    */
  export const enum CenterMarkDisplayTypes {
    OffCenterMarkDisplayType,
    AllHolesCenterMarkDisplayType,
    AllFilletsCenterMarkDisplayType,
    AllCircularEdgesCenterMarkDisplayType,
    AllPunchesCenterMarkDisplayType,
  }

  /**
    Center line display options for cylindrical features.
    @experimental
    */
  export const enum CenterLineDisplayTypes {
    OffCenterLineDisplayType,
    AllCylindricalCenterLineDisplayType,
    AllHolesCenterLineDisplayType,
  }

  /**
    Object that represents a Fusion 360 drawing document.
    */
  export class DrawingDocument extends core.Document {
    /**
      Returns the Drawing product object associated with this drawing document.
      */
    readonly drawing: Drawing;
  }

  /**
    Object that represents the drawing specific data within a drawing document.
    */
  export class Drawing extends core.Product {
    /**
      Returns the DrawingExportManager for this drawing.  You use the ExportManager
      to export the drawing in various formats.
      */
    readonly exportManager: DrawingExportManager;
    /**
      Returns the Sheets object that provides access to sheets in this drawing.
      @hidden
      */
    readonly sheets: Sheets;
    /**
      Returns the current sheet i.e, the active sheet
      @experimental
      */
    readonly activeSheet: Sheet;
  }

  /**
    Application-level drawing functionality. Access via the static get property.
    @experimental
    */
  export class DrawingManager extends core.Base {
    /**
      Returns the DrawingManager singleton instance.
      @returns DrawingManager object, or null on failure.
      */
    static get(): DrawingManager | null;
    /**
      Creates an input object that is used to define all of the settings needed to create a new drawing.
      After editing the returned input object, you can use it as input to a create method to create the new drawing.
      Note: Currently only AutomaticDrawingCreationMode is supported.
      @param design DataFile containing the source design.
      @param creationMode The drawing creation mode. Only AutomaticDrawingCreationMode is currently supported.
      @returns CreateDrawingInput object, or null on failure.
      */
    createDrawingInput(design: core.DataFile, creationMode: DrawingCreationModes): CreateDrawingInput | null;
    /**
      Creates an drawing document based on the settings defined in the input object.
      @param input A CreateDrawingInput object that was created using the createDrawingInput method on the DrawingManager object.
      @returns DataFile of created drawing, or null on failure.
      */
    createDrawing(input: CreateDrawingInput): core.DataFile | null;
  }

  /**
    Input parameters for drawing creation. Create via DrawingManager.createDrawingInput().
    @experimental
    */
  export class CreateDrawingInput extends core.Base {
    /**
      Gets and sets the drawing creation mode. Default: AutomaticDrawingCreationMode.
      */
    creationMode: DrawingCreationModes;
    /**
      Gets and sets which assembly content is included for automatic drawing creation:
      full assembly or visible-only. Default: FullAssemblyDrawingContentType.
      */
    content: DrawingContentTypes;
    /**
      Gets and sets the base document type option for drawing creation. Specifies whether to create from scratch or from a template.
      Default: FromScratchBaseDocumentType.
      */
    baseDocumentType: BaseDocumentTypes;
    /**
      Gets and sets the drawing standard (ISO or ASME). Default: ISODrawingStandardType.
      */
    standard: DrawingStandardTypes;
    /**
      Gets or sets the template file to use when creating the drawing.
      
      / This value is only used when {@link baseDocumentType} is set to
      / FromTemplateBaseDocumentType. If {@link FromScratchBaseDocumentType} is set to FromScratch,
      this value is ignored.
      
      If? FromTemplateBaseDocumentType is selected in baseDocumentType and this value is null or invalid,
      the createDrawing API will fail.
      */
    templateFile: core.DataFile;
    /**
      Gets and sets the drawing units (mm or inch). Default: MillimeterDrawingUnitType.
      */
    units: DrawingUnitTypes;
    /**
      Gets and sets the sheet size. This defaults to A3ISOSheetSize.
      Check the drawing standard via the standard property before setting ? ISO sizes (A0?A4) are only
      applicable when the standard is ISO, and ASME sizes (A?E) are only applicable when the standard
      is ASME. Setting a size that does not match the active standard will have no effect.
      To specify a custom sheet size, use the setCustomSheetSize method instead ? CustomSheetSize cannot be set directly.
      When the standard is ISO and the sheet size is A0ISOSheetSize, orientation cannot be set to PortraitSheetOrientationType.
      When the standard is ASME and the sheet size is EASMESheetSize, orientation cannot be set to PortraitSheetOrientationType.
      */
    sheetSize: SheetSizes;
    /**
      Gets or sets the custom sheet size for the drawing.
      @remarks
      
      The width and height values in {@link CustomSheetSize} are unitless; the unit is
      determined by the value set via the units API. By default, ISO drawings use millimeters
      and ASME drawings use inches.
      
      If a custom size has not been set, the getter returns a default {@link CustomSheetSize}
      object, which can be modified and passed back via the setter to apply it.
      
      For drawing creation, horizontalZones and verticalZones must each be at least 2 (positive integers).
      @param customSize A {@link CustomSheetSize} object defining the width, height, horizontal zones,
      and vertical zones.
      @returns Returns true if the custom size was set successfully, otherwise false.
      */
    customSize: CustomSheetSize;
    /**
      Gets and sets the sheet orientation. Default: LandscapeSheetOrientationType.
      PortraitSheetOrientationType is not supported when the standard is ISO and sheet size is A0ISOSheetSize,
      or when the standard is ASME and sheet size is EASMESheetSize.
      */
    orientationType: SheetOrientationTypes;
    /**
      Gets and sets which hierarchy levels get sheets. FirstLevelOnlySheetCreationType reduces file size. Default: AllLevelsSheetCreationType.
      */
    sheetCreationType: SheetCreationTypes;
    /**
      Gets the AutomationPreferences for configuring global, assembly, component, and sheet metal
      sheet settings. Modifications to the returned object directly affect drawing creation.
      */
    readonly automationPreferences: AutomationPreferences;
  }

  /**
    Custom width and height cannot exceed 5000 mm ? 5000 mm (millimeter units) or 200 inch ? 200 inch (inch units).
    Horizontal and vertical zone counts cannot exceed 1000.
    @experimental
    */
  export class CustomSheetSize extends core.Base {
    /**
      Gets and sets the width of the sheet.
      */
    width: number;
    /**
      Gets and sets the height of the sheet.
      */
    height: number;
    /**
      Gets and sets horizontal zones. Minimum 2 for drawing creation.
      */
    horizontalZones: number /*int*/;
    /**
      Gets and sets vertical zones. Minimum 2 for drawing creation.
      */
    verticalZones: number /*int*/;
  }

  /**
    Central configuration hub for automatic drawing preferences. Access globalPreferences for sheet
    generation toggles, and type-specific preferences for each sheet type.
    @experimental
    */
  export class AutomationPreferences extends core.Base {
    /**
      Gets GlobalPreferences for sheet generation toggles, auto-dimensioning, and component omission rules.
      */
    readonly globalPreferences: GlobalPreferences;
    /**
      Gets preferences for main (top-level) assembly sheets: ISO views, orthogonal views, dimensions, view appearance.
      */
    readonly mainAssemblyPreferences: AssemblyPreferences;
    /**
      Gets preferences for sub-assembly sheets: ISO views, orthogonal views, dimensions, view appearance.
      */
    readonly subAssemblyPreferences: AssemblyPreferences;
    /**
      Gets preferences for animation/exploded view sheets. Enable via GlobalPreferences.generateAnimationSheet.
      */
    readonly animationPreferences: AnimationPreferences;
    /**
      Gets preferences for individual component (part) sheets: views, dimensions, view appearance.
      */
    readonly componentPreferences: ComponentPreferences;
    /**
      Gets preferences for sheet metal folded model sheets (formed state). Complements flat pattern sheets.
      */
    readonly foldedModelPreferences: FoldedModelPreferences;
    /**
      Gets preferences for sheet metal flat pattern sheets (unfolded state with bend information).
      */
    readonly flatPatternPreferences: FlatPatternPreferences;
  }

  /**
    Global preferences for drawing generation: sheet toggles, auto-dimensioning, component omission.
    @experimental
    */
  export class GlobalPreferences extends core.Base {
    /**
      Gets and sets comma-separated keywords to omit components by name. Default: "Bolt,Screw,Nut,Washer".
      */
    omitComponentsWithKeywords: string;
    /**
      Gets and sets whether to auto-detect and omit fasteners by geometry. Default: false.
      */
    isDetectAndOmitFasteners: boolean;
    /**
      Gets and sets whether to generate main assembly sheets. Default: true.
      */
    isMainAssemblySheetGenerated: boolean;
    /**
      Gets and sets whether to generate sub-assembly sheets. Default: true.
      */
    isSubAssemblySheetGenerated: boolean;
    /**
      Gets and sets whether to generate animation/exploded view sheets. Default: false.
      */
    isAnimationSheetGenerated: boolean;
    /**
      Gets and sets whether to generate component (part) sheets. Default: true.
      */
    isComponentSheetGenerated: boolean;
    /**
      Gets and sets whether to generate folded model sheets for sheet metal. Default: true.
      */
    isFoldedModelSheetGenerated: boolean;
    /**
      Gets and sets whether to generate flat pattern sheets for sheet metal. Default: true.
      */
    isFlatPatternSheetGenerated: boolean;
    /**
      Gets and sets whether to enable auto-dimensioning on generated views. Default: true.
      */
    isAutoDimensionEnabled: boolean;
  }

  /**
    Preferences for assembly sheets (main and sub-assembly). Includes ISO view, orthogonal views, and parts list options.
    The same AssemblyPreferences class is used for both main assembly and sub-assembly configurations.
    @experimental
    */
  export class AssemblyPreferences extends core.Base {
    /**
      Gets settings for the isometric view sheet. Configure parts list inclusion and location.
      */
    readonly isoViewSheetPreferences: AssemblySheetPreferences;
    /**
      Gets settings for the orthogonal views sheet. Configure parts list inclusion and location.
      */
    readonly orthogonalViewSheetPreferences: AssemblySheetPreferences;
    /**
      Gets auto-dimension settings (strategy, hole preferences). Requires GlobalPreferences.enableAutoDimension.
      */
    readonly autoDimensionPreferences: AutoDimensionBasePreferences;
    /**
      Gets view appearance settings (style, edges, center marks, center lines).
      */
    readonly drawingViewPreferences: DrawingViewPreferences;
  }

  /**
    Preferences for animation/exploded view sheets. Enable via GlobalPreferences.generateAnimationSheet (default: false).
    @experimental
    */
  export class AnimationPreferences extends core.Base {
    /**
      Gets view appearance settings. Consider shaded styles for animation views.
      */
    readonly drawingViewPreferences: DrawingViewPreferences;
  }

  /**
    Preferences for individual component (part) sheets with views, dimensions, and annotations.
    @experimental
    */
  export class ComponentPreferences extends core.Base {
    /**
      Gets view generation preferences for component sheets. Controls whether orthogonal projection views
      (front, top, right side) are added to the sheet, and whether an optional isometric view is included.
      */
    readonly sheetViewPreferences: ComponentSheetViewPreferences;
    /**
      Gets auto-dimension settings (strategy, origin, patterns). Requires GlobalPreferences.enableAutoDimension.
      */
    readonly autoDimensionPreferences: AutoDimensionComponentPreferences;
    /**
      Gets view appearance settings (style, edges, center marks, center lines).
      */
    readonly drawingViewPreferences: DrawingViewPreferences;
  }

  /**
    Preferences for sheet metal folded model sheets (formed state). Complements flat pattern sheets.
    @experimental
    */
  export class FoldedModelPreferences extends core.Base {
    /**
      Gets view generation preferences for folded model sheets. Controls whether orthogonal projection views
      (front, top, right side) are added to the sheet, and whether an optional isometric view is included.
      */
    readonly sheetViewPreferences: ComponentSheetViewPreferences;
    /**
      Gets auto-dimension settings (strategy, origin, patterns). Requires GlobalPreferences.enableAutoDimension.
      */
    readonly autoDimensionPreferences: AutoDimensionComponentPreferences;
    /**
      Gets view appearance settings (style, edges, center marks, center lines).
      */
    readonly drawingViewPreferences: DrawingViewPreferences;
  }

  /**
    Preferences for sheet metal flat pattern sheets (unfolded state with bend information).
    @experimental
    */
  export class FlatPatternPreferences extends core.Base {
    /**
      Gets flat pattern sheet settings: folded model view, bend table, table location.
      */
    readonly orthogonalViewSheetPreferences: FlatPatternOrthogonalViewPreferences;
    /**
      Gets auto-dimension settings (strategy, origin, patterns). Requires GlobalPreferences.enableAutoDimension.
      */
    readonly autoDimensionPreferences: AutoDimensionComponentPreferences;
    /**
      Gets view appearance settings with flat pattern-specific options like bend extents.
      */
    readonly drawingViewPreferences: DrawingViewFlatPatternPreferences;
  }

  /**
    Preferences for assembly sheet views (both ISO and orthogonal). Configure parts list and view sheet creation.
    Used for both isometric and orthogonal projection sheet configurations.
    Default: Parts list IS included for ISO views, NOT included for orthogonal views.
    @experimental
    */
  export class AssemblySheetPreferences extends core.Base {
    /**
      Gets and sets whether to include a parts list (BOM) on the sheet. Default: true for ISO views, false for orthogonal views.
      Applicable only when isSheetCreated is true.
      */
    isPartsListIncluded: boolean;
    /**
      Gets and sets the corner location for the parts list table. Only applies when isPartsListIncluded is true.
      Default: TopRightTableLocationType for ISO views, TopLeftTableLocationType for orthogonal views.
      */
    partsListLocationType: TableLocationTypes;
    /**
      Gets and sets whether to create the view sheet (ISO or orthogonal). Default: true.
      */
    isSheetCreated: boolean;
  }

  /**
    Base auto-dimension settings: enable, strategy, hole preferences.
    Applicable only when GlobalPreferences.isAutoDimensionEnabled is true.
    @experimental
    */
  export class AutoDimensionBasePreferences extends core.Base {
    /**
      Gets and sets whether auto-dimensioning is enabled for this sheet type. Default: true.
      */
    isAutoDimensionEnabled: boolean;
    /**
      Gets and sets the dimension placement strategy. Default: OverallDimensionStrategyType.
      */
    dimensionStrategyType: DimensionStrategyTypes;
    /**
      Gets and sets hole and thread annotation preferences. Default: HoleAndThreadNoteHolePreferencesType.
      */
    holePreferencesType: HolePreferencesTypes;
  }

  /**
    Drawing view appearance settings: style, edges, center marks, center lines.
    @experimental
    */
  export class DrawingViewPreferences extends core.Base {
    /**
      Gets and sets the visual rendering style. Default: VisibleEdgesDrawingViewStyleType.
      */
    style: DrawingViewStyleTypes;
    /**
      Gets and sets the tangent edge display mode for the drawing view. Controls how tangent edges
      (edges where two tangent faces meet) are displayed. Default: OffTangentEdgeDisplayType.
      */
    tangentEdgesType: TangentEdgeDisplayTypes;
    /**
      Gets and sets whether interference edges are shown in the drawing view. Default: true for standard views, false for flat patterns.
      */
    isShowInterferenceEdges: boolean;
    /**
      Gets and sets whether thread representations are shown in the drawing view. Default: true for standard views, false for flat patterns.
      */
    isShowThreadEdges: boolean;
    /**
      Gets and sets the center mark display mode for the drawing view. Controls which circular features
      (holes, fillets, punches) display center marks. Default: OffCenterMarkDisplayType.
      */
    centerMarkType: CenterMarkDisplayTypes;
    /**
      Gets and sets the center line display mode for the drawing view. Controls which cylindrical features
      (holes, shafts) display center lines. Default: OffCenterLineDisplayType.
      */
    centerLineType: CenterLineDisplayTypes;
  }

  /**
    Preferences for component sheet views. Configure orthographic view creation and optional isometric view.
    This class provides settings for controlling which views are generated on component sheets, including
    standard orthographic projections (front, top, right side) and an optional isometric view.
    @experimental
    */
  export class ComponentSheetViewPreferences extends core.Base {
    /**
      Gets and sets whether to add orthogonal projection views (front, top, side) for the component.
      When true, the system will automatically generate standard orthographic projection views
      (front, top, and right side views) arranged on the sheet. Default: true.
      */
    isOrthogonalViewAdded: boolean;
    /**
      Gets and sets whether to add an isometric view alongside orthogonal views. Default: false.
      Applicable only when isOrthogonalViewAdded is true.
      */
    isIsometricViewAdded: boolean;
  }

  /**
    Auto-dimension settings for components. Extends base with origin and pattern options.
    @experimental
    */
  export class AutoDimensionComponentPreferences extends drawing.AutoDimensionBasePreferences {
    /**
      Gets and sets the datum origin for dimension placement. Default: ModelOriginDefaultOriginType.
      */
    defaultOriginType: DefaultOriginTypes;
    /**
      Gets and sets whether to include dimensions for circular pattern features. Default: true.
      */
    isCircularPatternDimensionsIncluded: boolean;
  }

  /**
    Preferences for flat pattern orthogonal view sheets. Configure folded model view, bend table.
    @experimental
    */
  export class FlatPatternOrthogonalViewPreferences extends core.Base {
    /**
      Gets and sets whether to add a folded model isometric view for reference on the flat pattern sheet. Default: false.
      */
    isFoldedModelIsometricViewAdded: boolean;
    /**
      Gets and sets whether to include a bend table with manufacturing data on the flat pattern sheet. Default: true.
      */
    isBendTableIncluded: boolean;
    /**
      Gets and sets the corner location for the bend table. Only applies when isBendTableIncluded is true. Default: TopLeftTableLocationType.
      */
    bendTableLocation: TableLocationTypes;
  }

  /**
    Drawing view settings for flat patterns. Adds bend extents. Different defaults than base.
    @experimental
    */
  export class DrawingViewFlatPatternPreferences extends drawing.DrawingViewPreferences {
    /**
      Gets and sets whether bend extent lines are displayed. Default: true.
      */
    isShowBendExtents: boolean;
  }

  /**
    Provides support to export the drawing in various formats.
    */
  export class DrawingExportManager extends core.Base {
    /**
      Defines the various settings for a STEP export.
      @param filename The name of the file to export to. Use settings on the returned PDFExportOptions
      object to change other settings.
      @returns Returns a PDFExportOptions object if successful and null if it should fail.
      */
    createPDFExportOptions(filename: string): PDFExportOptions | null;
    /**
      Executes the export operation to create the file in the format specified by the input ExportOptions object.
      @param exportOptions A DrawingExportOptions object that is created using one of the create methods on the DrawingExportManager object.
      This defines the type of export and defines the options supported for that file type.
      @returns Returns true if the export was successful.
      */
    execute(exportOptions: DrawingExportOptions): boolean;
  }

  /**
    The base class for the different drawing export types.  This class is never directly used
    in an export because you need the specific export type to specify the type of
    export to be performed.
    */
  export class DrawingExportOptions extends core.Base {
    /**
      Gets and sets the filename that the exported file will be written to.
      */
    filename: string;
  }

  /**
    Defines the inputs needed to export the drawing as PDF.
    */
  export class PDFExportOptions extends DrawingExportOptions {
    /**
      Defines which sheets to export.  Defaults to AllPDFSheets which
      will create a single PDF file containing all sheets in the drawing.
      
      the SelectedPDFSheets and CurrentPDFSheet options are dependent on
      the current selections in the user interface.
      
      To set this to RangePDFSheets, use the sheetRange property to define
      the range of sheets to print.
      */
    sheetsToExport: PDFSheetsExport;
    /**
      Defines the range of sheets to export. This can be a string like
      "1-3" or "1-2,5" where you can define a range of sheets and also
      specific sheets. Setting this property will automatically set
      the sheetsToExport setting to SelectedPDFSheets.
      */
    sheetRange: string;
    /**
      Specifies that the PDF file will be opened after export.
      */
    openPDF: boolean;
    /**
      Specifies if line weights should be used in the exported PDF file.
      */
    useLineWeights: boolean;
  }

  /**
    The various options that define which sheets to print.
    */
  export const enum PDFSheetsExport {
      /// Exports all of the sheets in the drawing as a single PDF file.
    AllPDFSheetsExport,
      /// Exports all of the current selected sheets in the drawing. The
      /// active sheet is always selected but the user can also select
      /// additional sheets.
    SelectedPDFSheetsExport,
      /// Exports the current active sheet.
    CurrentPDFSheetExport,
      /// Exports a defined range of sheets.
    RangePDFSheetsExport,
  }

  /**
    Provides access to the sheets in a drawing document.
    @hidden
    */
  export class Sheets extends core.Base {
    /**
      Returns the number of sheets on the drawing.
      */
    readonly count: number /*unsigned int*/;
  }

  /**
    Object that represents the sheet specific data within a drawing document.
    @experimental
    */
  export class Sheet extends core.Base {
    /**
      Returns the CustomTables collection for this sheet. Use this collection
      to access existing custom tables or create new ones.
      */
    readonly customTables: CustomTables;
  }

  /**
    Collection object that provides access to all custom tables on a sheet and supports creating new tables.
    Obtained via the Sheet.customTables property.
    @experimental
    */
  export class CustomTables extends core.Base {
    /**
      Returns the number of custom tables on the sheet associated with this collection.
      @hidden
      */
    readonly count: number /*unsigned int*/;
    /**
      Returns the specified custom table using an index into the collection.
      @param index The index of the custom table within the collection to return. The first item in the collection has an index of 0.
      @returns Returns the specified custom table or an error if an invalid index was specified.
      @hidden
      */
    item(index: number /*unsigned int*/): CustomTable;
    /**
      Creates a new CustomTableInput object that is used to define the properties needed to create a custom table.
      After configuring the returned input object, pass it to the add method to create the table.
      @returns Returns the newly created CustomTableInput object, or null if creation failed.
      @experimental
      */
    createInput(): CustomTableInput | null;
    /**
      Creates a custom table on the sheet based on the provided input settings.
      @param input A CustomTableInput object created using the CustomTables.createInput method.
      @returns Returns the newly created CustomTable object or null in the case of failure.
      @experimental
      */
    add(input: CustomTableInput): CustomTable | null;
  }

  /**
    The input object that defines the required input to create a Custom table when using the
    CustomTables.add method. Created using the CustomTables.createInput method.
    @experimental
    */
  export class CustomTableInput extends core.Base {
    /**
      Gets and sets the number of columns in the table.
      */
    columnCount: number /*int*/;
    /**
      Gets and sets the number of rows in the table. This does not include the header row.
      */
    rowCount: number /*int*/;
  }

  /**
    Base class for all table objects in a drawing.
    @experimental
    */
  export class Table extends core.Base {
    /**
      Returns the number of columns in the table.
      */
    readonly columnCount: number /*int*/;
    /**
      Returns the number of rows in the table. This does not include the header row.
      */
    readonly rowCount: number /*int*/;
  }

  /**
    Represents a custom table on a drawing sheet.
    @experimental
    */
  export class CustomTable extends Table {
    /**
      Updates the content of a specific cell in the custom table.
      @param rowIndex The zero-based row index of the cell to update.
      @param columnIndex The zero-based column index of the cell to update.
      @param data The string data to set in the specified cell.
      @returns Returns true if the content is modified successfully, otherwise returns false.
      */
    setCellData(rowIndex: number /*int*/, coulmnIndex: number /*int*/, data: string): boolean;
  }
}

