// Copyright (C) 2026 Autodesk Inc.
// All rights reserved.

// API Version "version".
// This file is generated by generateTypeScript.py from NIDL.
// Do not edit.

import { fusion, fusion as adsk_fusion } from './fusion';
import { core, core as adsk_core } from './core';

declare namespace adsk {
  export import fusion = adsk_fusion;
  export import core = adsk_core;
}

export namespace volume {

  /**
    Graph types for a volumetric model.
    @experimental
    */
  export const enum GraphTypes {
      /// The main graph containing the boundary, density, colour and UVW mapping subgraphs.
    PrimaryGraphType,
      /// The graph for the cell that is repeated across the volume.
    CellGraphType,
  }

  /**
    The main volumetric graph object. It has a parent component and is defined in this parent component's space.
    It also contains the primary and cell graphs.
    @experimental
    */
  export class VolumetricModel extends core.Base {
    /**
      Returns a graph from the volumetric model.
      @param graphType Which kind of graph to return.
      */
    getGraph(graphType: GraphTypes): Graph;
    /**
      Is the light bulb / eye (as displayed in the browser) controlling the model's visibility on.
      */
    isLightBulbOn: boolean;
    /**
      Returns the parent Component.
      */
    readonly parentComponent: adsk.fusion.Component;
    /**
      Get or set the main boundary body for this volumetric model.
      The volumetric model is bound by the axis aligned bounding box and will only be
      rendered within this body.
      */
    readonly boundaryBody: core.Base;
    /**
      De-register the Signed Distance Field callback handler with the given ID.
      @param id The ID used in registerCustomSDFCallback()
      @returns True if removed successfully. False otherwise.
      */
    removeCustomSDFCallback(id: string): boolean;
    /**
      Creates a VolumetricSampler object that can be used to sample the volumetric model.
      @returns Returns a VolumetricSampler object that will sample this VolumetricModel.
      */
    createSampler(): VolumetricSampler;
  }

  /**
    The VolumetricSampler object which is used for controled sampling of the volumetric model.
    @experimental
    */
  export class VolumetricSampler extends core.Base {
    /**
      Sets sample points to be used for sampling the volumetric model.
      This will override any previously set sample points and result in an unstructured sampling layout.
      @param samplePoints The sample points to be used for sampling the volumetric model.
      @returns True if the sample points were set successfully.
      */
    setSamplePoints(samplePoints: adsk.core.Point3D[]): boolean;
    /**
      Appends sample points to the existing sample points to be used for sampling the volumetric model.
      Adding sample points results in an unstructured sampling layout.
      @param samplePoints The sample points to be added to the sampler.
      */
    addSamplePoints(samplePoints: adsk.core.Point3D[]): boolean;
    /**
      Clears the sample points that have been set for sampling the volumetric model.
      This will reset the structured sampling rank to 0.
      @returns True if the sample points were successfully cleared.
      */
    clearSamplePoints(): boolean;
    /**
      Calculates and sets the sample points to be used for sampling the volumetric model for a given resolution throughout
      the bounding box provided. This will override any previously set sample points.
      @param elementSize The approximate spacing between sample points. The units used for the element size are centimeters.
      @param boundingBox3d The bounding box in which the sample points will be distributed.
      @returns True if the sample points were set successfully.
      */
    setBoundingBoxSampling(elementSize: number, boundingBox3d: adsk.core.BoundingBox3D): boolean;
    /**
      Calculates and sets the sample points to be used for sampling the volumetric model for a given resolution, plane
      and primary axis. The points will be distributed in a grid pattern on the plane, starting at the plane origin and
      extend in the primary axis and secodary axis for the axis size arguments. The secondary axis is calculated from the
      cross product of the plane normal and the primary axis. This will override any previously set sample points.
      @param elementSize The approximate spacing between sample points. The units used for the element size are centimeters.
      @param plane The plane on which the points will be distributed.
      @param primaryAxis The primary axis of the plane. This vector should be on the plane. The secondary axis
      of the plane is calculated as the cross-product of the plane normal and the primary axis
      @param primaryAxisSize The size of the plane in the primary axis direction.
      @param secondaryAxisSize The size of the plane in the secondary axis direction.
      @returns True if the sample points were set successfully.
      */
    setPlaneSampling(elementSize: number, plane: adsk.core.Plane, primaryAxis: adsk.core.Vector3D, primaryAxisSize: number, secondaryAxisSize: number): boolean;
    /**
      Gets the rank of the current structured sampling layout.
      This is 0 for unstructured sampling, 2 for plane grid sampling and 3 for bounding box grid sampling.
      */
    readonly structuredSamplingRank: number /*unsigned int*/;
    /**
      Gets the dimensions of the current structured sampling layout.
      For plane grid sampling this returns [primaryCount, secondaryCount].
      For bounding box grid sampling this returns [xCount, yCount, zCount].
      For unstructured sampling this returns an empty array.
      */
    readonly sampleDimensions: number[] /*unsigned int[]*/;
    /**
      Gets the spacing between neighbouring samples along each structured sampling axis.
      For unstructured sampling this returns an empty array.
      */
    readonly sampleSpacings: number[];
    /**
      Gets the origin of the current structured sampling layout.
      For plane grid sampling this is the plane origin.
      For bounding box grid sampling this is the minimum corner of the bounding box.
      Returns null if the current sampling layout is not structured.
      */
    readonly sampleOrigin: adsk.core.Point3D;
    /**
      Gets the axes of the current structured sampling layout.
      For plane grid sampling this returns [primaryAxis, secondaryAxis].
      For bounding box grid sampling this returns [xAxis, yAxis, zAxis].
      For unstructured sampling this returns an empty array.
      */
    readonly sampleAxes: adsk.core.Vector3D[];
    /**
      Gets the number of sample points that will be used for sampling the volumetric model.
      @returns The number of sample points that will be used for sampling the volumetric model.
      */
    samplePointCount(): number /*unsigned int*/;
    /**
      Evaluates the volumetric model at the previously set sample points for the given node and returns the results.
      @param graphNode The graph node to evaluate at the sample points.
      @param isOutput Optional argument that controls the sampling. If set to true samples an output pin, if set to false samples an input pin. Default is True.
      @param index Optional argument that controls the index of the pin to sample. Default is 0 which is the first pin.
      @returns An array of VolumetricSample objects that contain the results of sampling the volumetric model.
      */
    evaluate(graphNode: GraphNode, isOutput?: boolean/* = true*/, index?: number /*int*//* = 0*/): VolumetricSample[];
    /**
      Evaluates the density of the model at the previously set sample points and returns the results. This value
      is what is used to determine the level set of the model.
      @returns An array of VolumetricScalarSample objects that contain the results of sampling the volumetric model.
      */
    evaluateDensity(): VolumetricScalarSample[];
    /**
      Evaluates the level set function of the model at the previously set sample points and returns the results.
      @returns An array of VolumetricScalarSample objectst that contain the results of sampling the volumetric model.
      */
    evaluateLevelSet(): VolumetricScalarSample[];
    /**
      Evaluates the color of the model at the previously set sample points and returns the results.
      @returns An array of VolumetricColorSample objects that contain the results of sampling the volumetric model.
      */
    evaluateColor(): VolumetricColorSample[];
  }

  /**
    The VolumetricSamples object which is a base class for containing the result of sampling the volumetric model an array of points.
    @experimental
    */
  export class VolumetricSample extends core.Base {
    /**
      Gets the location of the sample evalution.
      */
    readonly point: adsk.core.Point3D;
  }

  /**
    The VolumetricColorSample object which contains the result of sampling a color value from the volumetric model at a point.
    @experimental
    */
  export class VolumetricColorSample extends VolumetricSample {
    /**
      Gets the color value at the sample point.
      */
    readonly value: adsk.core.Color;
  }

  /**
    The VolumetricScalarSample object which contains the result of sampling a scalar value from the volumetric model at a point.
    @experimental
    */
  export class VolumetricScalarSample extends VolumetricSample {
    /**
      Gets the scalar value at the sample point.
      */
    readonly value: number;
  }

  /**
    The VolumetricVectorSample object which contains the result of sampling a vector value from the volumetric model at a point.
    @experimental
    */
  export class VolumetricVectorSample extends VolumetricSample {
    /**
      Gets the vector value at the sample point.
      */
    readonly value: adsk.core.Vector3D;
  }

  /**
    Types of graph output nodes for the main graph.
    @experimental
    */
  export const enum GraphOutputNodeTypes {
      /// Scalar. Distance field of the boundary object of the model.
      /// Only used in the primary graph.
    BoundarySDFOutputNodeType,
      /// Scalar. Density/solidity of the volumetric model lattice at all points within it.
      /// Only used in the primary graph.
    LatticeDensityOutputNodeType,
      /// RGBA. The color of the model at all points within it.
      /// Only used in the primary graph.
    ColorOutputNodeType,
      /// Vector3. The coordinate system for the lattice cells. Mapping from the global xyz coordinates to lattice cell coordinates.
      /// Only used in the primary graph.
    LatticeCoordinatesOutputNodeType,
      /// Scalar. Strength of the volumetric model texture at all points within it.
      /// Only used in the primary graph.
    TextureDensityOutputNodeType,
      /// Vector3. The coordinate system for the volumetric texture cells. Mapping from the global xyz coordinates to texture cell coordinates.
      /// Only used in the primary graph.
    TextureCoordinatesOutputNodeType,
      /// Scalar. Defines the shape of the volumetric lattice cell.
      /// Only used in the cell graph.
    CellLatticeShapeOutputNodeType,
      /// Scalar. Defines the shape of the volumetric texture cell.
      /// Only used in the cell graph.
    CellTextureShapeOutputNodeType,
  }

  /**
    A simple read-only structure that represents a connection beween two nodes' pins in the graph.
    @experimental
    */
  export class GraphConnector extends core.Base {
    /**
      The node on the output of which this connector starts.
      */
    readonly sourceGraphNode: GraphNode;
    /**
      The output pin index of the start node.
      */
    readonly sourcePinIndex: number /*unsigned int*/;
    /**
      The node on the input of which this connector ends.
      */
    readonly targetGraphNode: GraphNode;
    /**
      The intput pin index of the end node.
      */
    readonly targetPinIndex: number /*unsigned int*/;
  }

  /**
    The graph that describes the volumetric model.
    Possible node types:
      "BoxSDF",
      "CylinderSDF",
      "SphereSDF",
      "TorusSDF",
      "PlaneSDF",
      "ReferencedGeometrySDF",
      "ReferencedCurveLength",
      "ReferencedCurveCoords",
      "ReferencedFaceCoords",
      "GradientVector",
      "InvertDensity",
      "PerlinNoiseScalar",
      "VoronoiNoiseScalar",
      "Shell",
      "ConstantScalar",
      "ConstantColor",
      "ImageSamplerScalar",
      "ImageSamplerVector",
      "ImageSamplerColor",
      "3DImageSamplerScalar",
      "SphereCoords",
      "TorusCoords",
      "CylinderCoords",
      "HomogenousTransformCoords",
      "TransformCoords",
      "AxisBasedDeformCoords ",
      "TwistCoords",
      "ControlPointMapScalarToScalar",
      "ControlPointMapScalarToColor",
      "FalloffMapping",
      "VectorToColor",
      "CombineScalarsToVector",
      "CombineScalarsToColor",
      "SplitVectorToScalars",
      "SplitColorToScalars",
      "LengthOfVector",
      "NormalizeVector",
      "ExternalColor",
      "FunctionScalarToScalar",
      "FunctionVectorToColor",
      "FunctionVectorToVector",
      "FunctionVectorToScalar",
      "BinaryOperatorColor",
      "BinaryOperatorVector",
      "BinaryOperatorScalar",
      "MultiplyColor",
      "MultiplyVector",
      "MultiplyScalar"
    @experimental
    */
  export class Graph extends core.Base {
    /**
      Get node with the given name.
      @param name Name to search for.
      @returns The node if found, null otherwise.
      */
    getNode(name: string): GraphNode | null;
    /**
      Get one of the special graph output nodes. Every graph has one or more, the cannot be created or added.
      The final output pins of the graph nodes should be connected to these to make a useful graph.
      @param outputNodeType The type of the output graph node.
      Not every graph has every type; the primary graph has all four ouput node types, the cell graph only has OutputDensity.
      @returns The output node if present in the graph, null otherwise.
      */
    getOutputNode(outputNodeType: GraphOutputNodeTypes): GraphNode | null;
    /**
      Get all the nodes in the graph, including the output nodes.
      @returns An array of nodes.
      */
    readonly allNodes: GraphNode[];
    /**
      Get all the possible node types that can be used as the nodeType parameter for addNode.
      */
    readonly allPossibleNodeTypes: string[];
    /**
      Add a new node to the graph. Node names are unique, attempting to add two nodes with the same name produces an error.
      @param name Name of the new node.
      @param nodeType The node type string, one of the types listed in the documentation.
      @returns The new node if it could be added, null otherwise.
      */
    addNode(name: string, nodeType: string): GraphNode | null;
    /**
      Get all the connectors in the graph.
      @returns An array of node connector objects, one for each connection between two nodes, unordered.
      */
    readonly allGraphConnectors: GraphConnector[];
    /**
      Get an upstream connection to the node's input pin.
      @param node The node in question.
      @param inputPinIndex The index of the input pin of the node.
      @returns An array of GraphConnector objects, one for each connection to another node.
      */
    getNodeInputPinConnector(node: GraphNode, inputPinIndex: number /*unsigned int*/): GraphConnector;
    /**
      Get an array of downstream connections from the node's output pin.
      @param node The node in question.
      @param outputPinIndex The index of the output pin of the node.
      @returns An array of GraphConnector objects, one for each connection to another node.
      */
    getNodeOutputPinConnectors(node: GraphNode, outputPinIndex: number /*unsigned int*/): GraphConnector[];
    /**
      Create a connection between nodes.
      @param outputNode The node where the connection starts.
      @param outputPinIndex The index of the output pin on the start node.
      @param inputNode The node where the connection ends.
      @param inputPinIndex The index of the input pin on the end node.
      */
    connect(outputNode: GraphNode, outputPinIndex: number /*unsigned int*/, inputNode: GraphNode, inputPinIndex: number /*unsigned int*/): boolean;
    /**
      Delete a connection between nodes.
      @param outputNode The node where the connection starts.
      @param outputPinIndex The index of the output pin on the start node.
      @param inputNode The node where the connection ends.
      @param inputPinIndex The index of the input pin on the end node.
      */
    disconnect(outputNode: GraphNode, outputPinIndex: number /*unsigned int*/, inputNode: GraphNode, inputPinIndex: number /*unsigned int*/): boolean;
    /**
      Check if all the channels in the graph can be evaluated and in a good state.
      @returns True if this graph can be evaluated, false otherwise.
      */
    canEvaluateGraph(): boolean;
  }

  /**
    Different types that graph nodes input and output types can be.
    @experimental
    */
  export const enum NodePinTypes {
    NoNodePinType,
    ScalarNodePinType,
    VectorNodePinType,
    ColorNodePinType,
  }

  /**
    An individual node within a graph.
    @experimental
    */
  export class GraphNode extends core.Base {
    /**
      The name of this graph node as give on creation. Node names for each graph should be unique.
      */
    name: string;
    /**
      Get the string node type that is was created with.
      */
    readonly nodeType: string;
    /**
      A user readable description that explains the function of this node type.
      */
    readonly description: string;
    /**
      Deletes the graphNode and all of its connections.
      @returns Returns true in the case where the deletion was successful.
      All properties and proery objects of this node will become invalid after this call.
      Output nodes cannot be deleted.
      */
    deleteMe(): boolean;
    /**
      Get a collection of all node properties supported by this node.
      @returns An object containing node properties.
      */
    readonly properties: GraphNodeProperties;
    /**
      How many input pins does this node have.
      @returns Pin count.
      */
    getInputPinCount(): number /*unsigned int*/;
    /**
      The name of this graph node input pin describing its function.
      @param pinIndex Zero based index of the pin to get. Should be less than the pin count.
      */
    getInputPinName(pinIndex: number /*unsigned int*/): string;
    /**
      Get the type of the node input pin.
      @param pinIndex Zero based index of the pin to get. Should be less than the pin count.
      @returns The pin type enum.
      */
    getInputPinType(pinIndex: number /*unsigned int*/): NodePinTypes;
    /**
      Some input pins can be optional, so they do not need to be connected for the node to work.
      @param pinIndex Zero based index of the pin to get. Should be less than the pin count.
      @returns True if pin is optional, false if it is required.
      */
    isInputPinOptional(pinIndex: number /*unsigned int*/): boolean;
    /**
      How many output pins does this node have.
      @returns Pin count.
      */
    getOutputPinCount(): number /*unsigned int*/;
    /**
      The name of this graph node input pin describing its function.
      @param pinIndex Zero based index of the pin to get. Should be less than the pin count.
      */
    getOutputPinName(pinIndex: number /*unsigned int*/): string;
    /**
      Get the type of the node output pin.
      @param pinIndex Zero based index of the pin to get. Should be less than the pin count.
      @returns The pin type enum.
      */
    getOutputPinType(pinIndex: number /*unsigned int*/): NodePinTypes;
    /**
      Check if the graph node properties are valid.
      @returns True if the node has good inputs for its properties, false otherwise.
      */
    hasValidProperties(): boolean;
  }

  /**
    A collection of properties of a graph node.
    @experimental
    */
  export class GraphNodeProperties extends core.Base {
    /**
      The number of items in the collection.
      */
    readonly count: number /*unsigned int*/;
    /**
      Function that returns the specified property using an index into the collection.
      @param index The index of the item within the collection to return.  The first item in the collection has an index of 0.
      @returns Returns the specified item or null if an invalid index was specified.
      */
    item(index: number /*unsigned int*/): GraphNodeProperty | null;
    /**
      Returns the property with the specified internal name.
      @param propertyName The id of the property.
      @returns Returns the specified property or null in the case where there is no property with the specified id.
      */
    itemByName(propertyName: string): GraphNodeProperty | null;
    [Symbol.iterator](): GraphNodePropertyIterator;
  }
  abstract class GraphNodePropertyIterator implements Iterator<volume.GraphNodeProperty>{
    next(): IteratorResult<volume.GraphNodeProperty, boolean | undefined>
  }

  /**
    Class for representing a property of a graph node. These can be of many types.
    @experimental
    */
  export class GraphNodeProperty extends core.Base {
    /**
      Gets the internal name of the property.
      */
    readonly name: string;
    /**
      Returns the description of this property.
      This description is localized and can change based on the current language.
      */
    readonly description: string;
  }

  /**
    A property value that is a string.
    @experimental
    */
  export class StringGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property.
      */
    value: string;
  }

  /**
    A property value that is a boolean.
    @experimental
    */
  export class BooleanGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property.
      */
    value: boolean;
  }

  /**
    A property value that is an integer.
    @experimental
    */
  export class IntegerGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property.
      */
    value: number /*int*/;
  }

  /**
    A property value that is a floating point value.
    @experimental
    */
  export class ScalarGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property.
      */
    value: number;
  }

  /**
    A property value that is a 3D vector.
    @experimental
    */
  export class Vector3DGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property.
      */
    value: adsk.core.Vector3D;
  }

  /**
    A property value that is a 3D Matrix.
    @experimental
    */
  export class Matrix3DGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property.
      */
    value: adsk.core.Matrix3D;
  }

  /**
    A property value that is a color.
    @experimental
    */
  export class ColorGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property.
      */
    value: adsk.core.Color;
  }

  /**
    Types of interpolation functions for the control point maps.
    @experimental
    */
  export const enum ControlPointInterpolators {
      /// The point values are interpolated linearly.
    LinearInterpolator,
      /// The value is set to the value of whichever point is nearest.
    NearestInterpolator,
      /// Point are interpolated using a cubic function.
    CubicInterpolator,
      /// Points are interpolated with smooth tangent transitions.
    SmoothInterpolator,
  }

  /**
    A read-only structure that represents a control point used in ScalarControlPointMapGraphNodeProperty.
    @experimental
    */
  export class ScalarControlPoint extends core.Base {
    /**
      The parameter inside the input domain of the control point map for this point.
      */
    readonly parameter: number;
    /**
      The output double value of the control point for this point.
      */
    readonly value: number;
    /**
      The interpolator function.
      */
    readonly interpolator: ControlPointInterpolators;
  }

  /**
    A read-only structure that represents a control point used in ColorControlPointMapGraphNodeProperty.
    @experimental
    */
  export class ColorControlPoint extends core.Base {
    /**
      The parameter inside the input domain of the control point map for this point.
      */
    readonly parameter: number;
    /**
      The output color value of the control point for this point.
      */
    readonly value: adsk.core.Color;
    /**
      The interpolator function.
      */
    readonly interpolator: ControlPointInterpolators;
  }

  /**
    A property value that defines a complex mapping curve from an input domain of double values to
    an output range of double values. The mapping is represented by a set of points ordered by
    their domain value parameters. For a given input value, the output value is interpolated from the values
    of the two points before and after it using the specified interpolation function for each point.
    @experimental
    */
  export class ScalarControlPointMapGraphNodeProperty extends GraphNodeProperty {
    /**
      The number of points.
      @returns Total point count.
      */
    readonly pointCount: number /*unsigned int*/;
    /**
      Get the point at index.
      @param index Index of the point to get.
      @returns The control point at this index.
      */
    getPoint(index: number /*unsigned int*/): ScalarControlPoint;
    /**
      Add a point to the map.
      @param parameter Where in the input domain where the point lies.
      @param value The double value of the parameter in the output domain.
      @param interpolator The function used to interpolate an output value for a input parameter between this point and the next.
      @returns True if successfully added.
      */
    addPoint(parameter: number, value: number, interpolator: ControlPointInterpolators): boolean;
    /**
      Remove a point from the map.
      @param index Index of the point to remove.
      @returns True if successfully removed.
      */
    removePoint(index: number /*unsigned int*/): boolean;
    /**
      Remove all points from the map.
      @returns True if successfully cleared.
      */
    clear(): boolean;
  }

  /**
    A property value that defines a complex mapping curve from an input domain of double values to
    an output range of color values. The mapping is represented by a set of points ordered by
    their domain value parameters. For a given input value, the output value is interpolated from the values
    of the two points before and after it using the specified interpolation function for each point.
    @experimental
    */
  export class ColorControlPointMapGraphNodeProperty extends GraphNodeProperty {
    /**
      The number of points.
      @returns Total point count.
      */
    readonly pointCount: number /*unsigned int*/;
    /**
      Get the point at index.
      @param index Index of the point to get.
      @returns The control point at this index.
      */
    getPoint(index: number /*unsigned int*/): ColorControlPoint;
    /**
      Add a point to the map.
      @param parameter Where in the input domain where the point lies.
      @param value The color value of the parameter in the output domain.
      @param interpolator The function used to interpolate an output value for a input parameter between this point and the next.
      @returns True if successfully added.
      */
    addPoint(parameter: number, value: adsk.core.Color, interpolator: ControlPointInterpolators): boolean;
    /**
      Remove a point from the map.
      @param index Index of the point to remove.
      @returns True if successfully removed.
      */
    removePoint(index: number /*unsigned int*/): boolean;
    /**
      Remove all points from the map.
      @returns True if successfully cleared.
      */
    clear(): boolean;
  }

  /**
    A geometry reference property that defines a BeamNetwork object which is
    commonly used in discrete lattice structures.
    @experimental
    */
  export class BeamNetwork extends core.Base {
    /**
      The creator function of the BeamNetwork object.
      */
    static create(): BeamNetwork;
    /**
      The vertices of the beam network. Each vertex is a Point3D.
      */
    vertices: adsk.core.Point3D[];
    /**
      The beams of the beam network. Each beam is a pair of vertex indices.
      The size of the array should be a multiple of 2, and equal to the length of the radii array.
      */
    beams: number[] /*unsigned int[]*/;
    /**
      The radii of the beams. Each radius is a double value. The radii define
      the radius of one end of the beam that corresponds to the same index in the beams array.
      The size of the array should be a multiple of 2, and equal to the length of the beams array.
      */
    radii: number[];
  }

  /**
    A property value that represents a link to a geometric object.
    @experimental
    */
  export class GeometryGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property. This should be one or more CAD geometry objects,
      such as a BREP or mesh bodies, faces or sketch curves. Setting this will override any
      value set by customSDFCallbackID.
      */
    value: core.Base[];
    /**
      The ID of a custom Signed Distance Field callback object registered with CustomSDFCallbackRegistry.
      Setting this will override any CAD geometry set previously.
      */
    customSDFCallbackID: string;
    /**
      Set the value of the property. The value should be a BeamNetwork object,
      which defines the geometry by defining vertices, beams and radii of the beams.
      */
    beamNetwork: BeamNetwork;
  }

  /**
    A property value that is provides a transform to a node. This is set with an Occurrence of a Component.
    @experimental
    */
  export class TransformRefGraphNodeProperty extends GraphNodeProperty {
    /**
      Get or set the value of the property. This should be the occurrence of a component.
      */
    value: fusion.Occurrence;
  }
}

